"use strict";
(() => {
  const root = document.documentElement;
  const key = "sonara:nexus:preferences:v1";
  const reduced = matchMedia?.("(prefers-reduced-motion: reduce)")?.matches ?? false;
  const defaults = { language:"en", theme:"system", motion:reduced?"off":"on", sound:"off", haptics:"on" };
  const dictionaries = {
    en:{platform:"Platform",businessBuilder:"Business Builder",creatorStudio:"Creator Studio",growthStudio:"Growth Studio",tools:"Free tools",pricing:"Pricing",support:"Support",login:"Log in",start:"Start Free",menu:"Menu",command:"Command",experience:"Experience",heroEyebrow:"Launch operating system",heroHeading:"Make work move.",heroBody:"Business Builder, Creator Studio, and Growth Studio connect through one fast operating layer for founders, creators, and small teams.",primaryAction:"Enter SONARA Nexus",secondaryAction:"Explore free tools",tertiaryAction:"See plans",productsKicker:"Three connected companies",productsHeading:"One operating layer. Three focused workspaces.",productsBody:"Business Builder, Creator Studio, and Growth Studio keep their own tools and records while identity, billing, support, and delivery stay connected through SONARA Nexus.",flowKicker:"Designed for momentum",flowHeading:"From intent to outcome without losing context.",ctaKicker:"Start with the next useful action",ctaHeading:"Build something real before adding complexity.",searchPlaceholder:"Search pages and actions",settingsTitle:"Experience settings",language:"Language",languageHelp:"Updates the interface and core product language.",appearance:"Appearance",appearanceHelp:"Follow your device or choose light or dark.",motion:"Motion",sound:"Sound feedback",haptics:"Tactile feedback"},
    es:{platform:"Plataforma",businessBuilder:"Business Builder",creatorStudio:"Creator Studio",growthStudio:"Growth Studio",tools:"Herramientas gratis",pricing:"Precios",support:"Soporte",login:"Iniciar sesión",start:"Comenzar gratis",menu:"Menú",command:"Comandos",experience:"Experiencia",heroEyebrow:"Sistema operativo de lanzamiento",heroHeading:"Haz que el trabajo avance.",heroBody:"Business Builder, Creator Studio y Growth Studio se conectan mediante una capa operativa rápida.",primaryAction:"Entrar a SONARA Nexus",secondaryAction:"Explorar herramientas gratis",tertiaryAction:"Ver planes",productsKicker:"Tres empresas conectadas",productsHeading:"Una capa operativa. Tres espacios enfocados.",productsBody:"Cada empresa conserva sus herramientas y registros mientras identidad, facturación, soporte y entrega permanecen conectados.",flowKicker:"Diseñado para el impulso",flowHeading:"De la intención al resultado sin perder el contexto.",ctaKicker:"Empieza con la siguiente acción útil",ctaHeading:"Construye algo real antes de añadir complejidad.",searchPlaceholder:"Buscar páginas y acciones",settingsTitle:"Ajustes de experiencia",language:"Idioma",languageHelp:"Actualiza la interfaz y el lenguaje principal del producto.",appearance:"Apariencia",appearanceHelp:"Sigue tu dispositivo o elige claro u oscuro.",motion:"Movimiento",sound:"Sonido",haptics:"Respuesta táctil"},
    fr:{platform:"Plateforme",businessBuilder:"Business Builder",creatorStudio:"Creator Studio",growthStudio:"Growth Studio",tools:"Outils gratuits",pricing:"Tarifs",support:"Assistance",login:"Connexion",start:"Commencer gratuitement",menu:"Menu",command:"Commande",experience:"Expérience",heroEyebrow:"Système d’exploitation de lancement",heroHeading:"Faites avancer le travail.",heroBody:"Business Builder, Creator Studio et Growth Studio se connectent dans une couche opérationnelle rapide.",primaryAction:"Entrer dans SONARA Nexus",secondaryAction:"Explorer les outils",tertiaryAction:"Voir les offres",productsKicker:"Trois entreprises connectées",productsHeading:"Une couche opérationnelle. Trois espaces spécialisés.",productsBody:"Chaque entreprise conserve ses outils et ses données tandis que l’identité, la facturation, l’assistance et la livraison restent connectées.",flowKicker:"Conçu pour l’élan",flowHeading:"De l’intention au résultat sans perdre le contexte.",ctaKicker:"Commencez par l’action utile",ctaHeading:"Construisez quelque chose de réel.",searchPlaceholder:"Rechercher des pages et actions",settingsTitle:"Réglages de l’expérience",language:"Langue",languageHelp:"Met à jour l’interface et le langage principal du produit.",appearance:"Apparence",appearanceHelp:"Suivez l’appareil ou choisissez clair ou sombre.",motion:"Animation",sound:"Retour sonore",haptics:"Retour tactile"},
    de:{platform:"Plattform",businessBuilder:"Business Builder",creatorStudio:"Creator Studio",growthStudio:"Growth Studio",tools:"Kostenlose Tools",pricing:"Preise",support:"Support",login:"Anmelden",start:"Kostenlos starten",menu:"Menü",command:"Befehl",experience:"Erlebnis",heroEyebrow:"Launch-Betriebssystem",heroHeading:"Arbeit in Bewegung bringen.",heroBody:"Business Builder, Creator Studio und Growth Studio sind über eine schnelle Betriebsebene verbunden.",primaryAction:"SONARA Nexus öffnen",secondaryAction:"Tools erkunden",tertiaryAction:"Pläne ansehen",productsKicker:"Drei verbundene Unternehmen",productsHeading:"Eine Betriebsebene. Drei fokussierte Arbeitsbereiche.",productsBody:"Jedes Unternehmen behält seine Werkzeuge und Daten, während Identität, Abrechnung, Support und Lieferung verbunden bleiben.",flowKicker:"Für Dynamik entwickelt",flowHeading:"Von der Absicht zum Ergebnis ohne Kontextverlust.",ctaKicker:"Mit dem nächsten Schritt beginnen",ctaHeading:"Etwas Echtes bauen.",searchPlaceholder:"Seiten und Aktionen durchsuchen",settingsTitle:"Erlebniseinstellungen",language:"Sprache",languageHelp:"Aktualisiert die Oberfläche und zentrale Produktsprache.",appearance:"Darstellung",appearanceHelp:"Gerät verwenden oder Hell/Dunkel wählen.",motion:"Bewegung",sound:"Klangfeedback",haptics:"Haptisches Feedback"}
  };
  let preferences;try{preferences={...defaults,...JSON.parse(localStorage.getItem(key)||"{}")} }catch{preferences={...defaults}}
  let audioContext;
  const resolveTheme=v=>v==="light"||v==="dark"?v:(matchMedia?.("(prefers-color-scheme: dark)")?.matches?"dark":"light");
  function translate(){const dict=dictionaries[preferences.language]||dictionaries.en;root.lang=preferences.language;document.querySelectorAll("[data-i18n]").forEach(el=>{const value=dict[el.dataset.i18n];if(!value)return;if(el instanceof HTMLInputElement&&el.type==="search")el.placeholder=value;else el.textContent=value})}
  function apply(){root.dataset.theme=resolveTheme(preferences.theme);root.dataset.nexusMotion=preferences.motion;root.dataset.nexusSound=preferences.sound;root.dataset.nexusHaptics=preferences.haptics;translate();document.querySelectorAll("[data-nexus-preference]").forEach(el=>{const name=el.dataset.nexusPreference;if(el.type==="checkbox")el.checked=preferences[name]==="on";else el.value=preferences[name]})}
  function hero(){if(!document.body.classList.contains("sonara-home-v3"))return;const stage=document.querySelector(".hero");if(!stage||stage.querySelector(".nexus-hero-visual"))return;stage.insertAdjacentHTML("beforeend",`<div class="nexus-hero-visual" aria-hidden="true"><div class="nexus-orbit" data-nexus-parallax><span class="nexus-ring"></span><span class="nexus-ring"></span><span class="nexus-ring"></span><span class="nexus-node nexus-node--forge"></span><span class="nexus-node nexus-node--canvas"></span><span class="nexus-node nexus-node--signal"></span><span class="nexus-orbit-label nexus-orbit-label--forge">Forge mode</span><span class="nexus-orbit-label nexus-orbit-label--canvas">Canvas mode</span><span class="nexus-orbit-label nexus-orbit-label--signal">Signal mode</span><span class="nexus-orbit-floor"></span></div></div>`)}
  function reveal(){const items=document.querySelectorAll("main>section:not(.hero),.nexus-section,.card,.nexus-product");items.forEach(x=>x.dataset.nexusReveal="");if(reduced||preferences.motion==="off"||!window.IntersectionObserver){items.forEach(x=>x.classList.add("is-visible"));return}const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add("is-visible");observer.unobserve(entry.target)}}),{threshold:.08});items.forEach(x=>observer.observe(x))}
  function parallax(){const target=document.querySelector("[data-nexus-parallax]");if(!target||reduced||preferences.motion==="off"||innerWidth<920)return;addEventListener("pointermove",event=>{const x=(event.clientX/innerWidth-.5)*8,y=(event.clientY/innerHeight-.5)*-7;target.style.transform = `rotateX(${y}deg) rotateY(${x}deg)`},{passive:true})}
  function tone(kind="tap"){if(preferences.sound!=="on")return;const AudioContext=window.AudioContext||window.webkitAudioContext;if(!AudioContext)return;audioContext ||= new AudioContext();const now=audioContext.currentTime,gain=audioContext.createGain(),osc=audioContext.createOscillator();osc.type="triangle";osc.frequency.value=kind==="open"?320:420;gain.gain.setValueAtTime(.03,now);gain.gain.exponentialRampToValueAtTime(.0001,now+.12);osc.connect(gain).connect(audioContext.destination);osc.start(now);osc.stop(now+.14)}
  function tactile(){addEventListener("pointerdown",event=>{const control=event.target.closest?.("a,button,summary");if(!control)return;control.classList.add("nexus-press");if(preferences.haptics==="on"&&navigator.vibrate)navigator.vibrate(7);tone(control.hasAttribute("data-nexus-command")?"open":"tap")});addEventListener("pointerup",()=>document.querySelectorAll(".nexus-press").forEach(x=>x.classList.remove("nexus-press")))}
  function dialogs(){const command=document.querySelector("#nexus-command-dialog"),settings=document.querySelector("#nexus-settings-dialog"),list=command?.querySelector(".nexus-command-list"),input=command?.querySelector("input");const links=[...document.querySelectorAll(".sonara-desktop-nav a")];if(list)list.innerHTML=links.map(a=>`<li><a href="${a.getAttribute("href")}" data-label="${a.textContent.toLowerCase()}"><span>${a.textContent}</span><small>↵</small></a></li>`).join("");const open=d=>{d?.showModal?.();setTimeout(()=>d===command&&input?.focus(),30)};document.querySelectorAll("[data-nexus-command]").forEach(b=>b.onclick=()=>open(command));document.querySelectorAll("[data-nexus-settings]").forEach(b=>b.onclick=()=>open(settings));document.querySelectorAll("[data-dialog-close]").forEach(b=>b.onclick=()=>b.closest("dialog")?.close());input?.addEventListener("input",()=>list?.querySelectorAll("li").forEach(li=>li.hidden=!li.textContent.toLowerCase().includes(input.value.toLowerCase())));addEventListener("keydown",event=>{if((event.metaKey||event.ctrlKey)&&event.key.toLowerCase()==="k"){event.preventDefault();open(command)}})}
  function settings(){document.querySelectorAll("[data-nexus-preference]").forEach(el=>el.addEventListener("change",()=>{const name=el.dataset.nexusPreference;preferences[name]=el.type==="checkbox"?(el.checked?"on":"off"):el.value;localStorage.setItem(key,JSON.stringify(preferences));apply()}))}
  function routes(){const progress=document.querySelector(".nexus-route-progress");document.addEventListener("click",event=>{const link=event.target.closest?.("a[href]");if(!link||event.metaKey||event.ctrlKey)return;const url=new URL(link.href,location.href);if(url.origin!==location.origin||url.hash)return;if(!document.startViewTransition){progress?.classList.add("is-active")}})}
  function init(){apply();hero();reveal();parallax();dialogs();settings();tactile();routes();root.classList.add("nexus-ready");root.classList.remove("nexus-loading");const loader=document.querySelector("#nexus-loader");if(loader)setTimeout(()=>loader.hidden=true,320)}
  if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",init,{once:true});else init();
})();
