export const supabaseIntegrationFeatureFlags = Object.freeze({
  SUPABASE_INTEGRATIONS_ENABLED: true,
  SUPABASE_BRANCHING_PREVIEW_ENABLED: true,
  SUPABASE_EDGE_FUNCTIONS_ENABLED: false,
  SUPABASE_QUEUES_ENABLED: false,
  SUPABASE_CRON_ENABLED: false,
  SUPABASE_DATABASE_WEBHOOKS_ENABLED: false,
  SUPABASE_REALTIME_DASHBOARDS_ENABLED: false,
  SUPABASE_VECTOR_SEARCH_ENABLED: false,
  SUPABASE_STORAGE_POLICY_ENABLED: true,
  SUPABASE_VAULT_POLICY_ENABLED: true,
  SUPABASE_WRAPPERS_REVIEW_ENABLED: true,
  SUPABASE_PROVIDER_HEALTH_CHECKS_ENABLED: false,
  SUPABASE_INTEGRATION_CONTROL_CENTER_ENABLED: true
});
