-- Deterministic cross-industry and research formula definitions.
-- Does not install executable SQL, widen RLS, or populate customer records.
-- Results remain organization-scoped through existing formula result routes.
INSERT INTO public.sonara_formula_definitions
  (formula_key,group_key,product_area,label,public_label,expression_text,required_inputs,target_tables,output_unit,role_visibility,status,notes)
VALUES
  ('loaded_labor_cost','employee_payroll','Business Builder','Loaded labor cost','Loaded labor cost','paid_hours * (hourly_wage + benefits_per_hour + employer_payroll_cost_per_hour)','["paid_hours","hourly_wage","benefits_per_hour","employer_payroll_cost_per_hour"]','[]','money','["owner","admin"]','active','Explicit-input estimate only; no regulatory certification, operational control or provider telemetry.'),
  ('weekly_wage_projection','employee_payroll','Business Builder','Weekly wage projection','Weekly wage projection','regular_hours * regular_rate + overtime_hours * regular_rate * overtime_multiplier','["regular_hours","regular_rate","overtime_hours","overtime_multiplier"]','[]','money','["owner","admin"]','active','Explicit-input estimate only; no regulatory certification, operational control or provider telemetry.'),
  ('billable_utilization_percent','employee_payroll','Business Builder','Billable utilization','Billable utilization','100 * billable_hours / paid_hours','["billable_hours","paid_hours"]','[]','percent','["owner","admin"]','active','Explicit-input estimate only; no regulatory certification, operational control or provider telemetry.'),
  ('opportunity_value_gap','operating_twin','Business Builder','Opportunity value gap','Opportunity value gap','alternative_net_value - selected_net_value','["alternative_net_value","selected_net_value"]','[]','money','["owner","admin"]','active','Explicit-input estimate only; no regulatory certification, operational control or provider telemetry.'),
  ('project_unit_margin_percent','operating_twin','Business Builder','Project margin','Project margin','100 * (bid_revenue - direct_cost - allocated_overhead) / bid_revenue','["bid_revenue","direct_cost","allocated_overhead"]','[]','percent','["owner","admin"]','active','Explicit-input estimate only; no regulatory certification, operational control or provider telemetry.'),
  ('material_quantity_with_waste','construction_trades','Business Builder','Material quantity including waste','Material quantity including waste','net_quantity * (1 + waste_percent / 100)','["net_quantity","waste_percent"]','[]','quantity','["owner","admin"]','active','Explicit-input estimate only; no regulatory certification, operational control or provider telemetry.'),
  ('concrete_volume_cubic_yards','construction_trades','Business Builder','Concrete volume including waste','Concrete volume including waste','length_feet * width_feet * depth_feet * (1 + waste_percent / 100) / 27','["length_feet","width_feet","depth_feet","waste_percent"]','[]','cubic_yards','["owner","admin"]','active','Explicit-input estimate only; no regulatory certification, operational control or provider telemetry.'),
  ('crew_duration_hours','construction_trades','Business Builder','Crew duration','Crew duration','labor_hours / crew_size','["labor_hours","crew_size"]','[]','hours','["owner","admin"]','active','Explicit-input estimate only; no regulatory certification, operational control or provider telemetry.'),
  ('trade_job_cost','construction_trades','Business Builder','Trade job cost','Trade job cost','labor_hours * loaded_hourly_cost + material_cost + equipment_cost + permit_cost','["labor_hours","loaded_hourly_cost","material_cost","equipment_cost","permit_cost"]','[]','money','["owner","admin"]','active','Explicit-input estimate only; no regulatory certification, operational control or provider telemetry.'),
  ('length_meters_from_feet','units_measurement','Business Builder','Feet to meters','Feet to meters','length_feet * 0.3048','["length_feet"]','[]','meters','["owner","admin"]','active','Explicit-input estimate only; no regulatory certification, operational control or provider telemetry.'),
  ('data_transfer_seconds','computing_encoding','Creator Studio','Ideal transfer time','Ideal transfer time','payload_mebibytes * 1048576 * 8 / throughput_bits_per_second','["payload_mebibytes","throughput_bits_per_second"]','[]','seconds','["owner","admin"]','active','Explicit-input estimate only; no regulatory certification, operational control or provider telemetry.'),
  ('base64_encoded_bytes','computing_encoding','Creator Studio','Base64 size','Base64 size','4 * ceil(payload_bytes / 3)','["payload_bytes"]','[]','bytes','["owner","admin"]','active','Explicit-input estimate only; no regulatory certification, operational control or provider telemetry.'),
  ('quantum_qubit_layer_shots','science_research','SONARA Lab','Quantum sampling workload proxy','Quantum sampling workload proxy','measured_qubits * circuit_depth * shot_count','["measured_qubits","circuit_depth","shot_count"]','[]','qubit_layer_shots','["owner","admin"]','active','Explicit-input estimate only; no regulatory certification, operational control or provider telemetry.'),
  ('earth_circular_orbit_period_minutes','science_research','SONARA Lab','Ideal Earth orbit period','Ideal Earth orbit period','2*pi*sqrt((6378.137 + altitude_km)^3 / 398600.4418) / 60','["altitude_km"]','[]','minutes','["owner","admin"]','active','Explicit-input estimate only; no regulatory certification, operational control or provider telemetry.'),
  ('telescope_diffraction_arcseconds','science_research','SONARA Lab','Ideal telescope angular resolution','Ideal telescope angular resolution','1.22 * (wavelength_nanometers*1e-9) / (aperture_millimeters*1e-3) * 206264.80624709636','["wavelength_nanometers","aperture_millimeters"]','[]','arcseconds','["owner","admin"]','active','Explicit-input estimate only; no regulatory certification, operational control or provider telemetry.')
ON CONFLICT (formula_key) DO NOTHING;
