-- Bring the published catalog rows in line with the catalog in code.
--
-- GENERATED by scripts/generate-catalog-sync-migration.cjs -- regenerate rather
-- than edit by hand.
--
-- /service-catalog merges service_catalog_items over the defaults in
-- lib/catalog/*.cjs, so the table wins wherever it holds a value. When the
-- product names were rewritten for customers, the table was left holding the
-- old ones -- including "SONARA Nexus Shared Operating Spine", a retired
-- public name AGENTS.md does not allow in active UI.
--
-- It also broke the production deploy: verify-production-product-catalog.mjs
-- compares these rows against the code and gates the release on them matching.
--
-- Nothing is inserted or deleted. Every service_key below was seeded by
-- 20260725180000_recommended_product_catalog.sql, so the update matches on
-- what is already there.
--
-- What is new here is the retirement step at the end, and it exists because
-- removing a product from lib/catalog/*.cjs did not remove it from the
-- product's page. /service-catalog reads service_catalog_items where
-- status = 'active' and merges those rows over the code defaults, so a row
-- the code had stopped listing carried on being published from the database --
-- with its old name, its old summary, and a route the customer could still
-- click. Deleting the row would take its history with it, so the retirement
-- flips status instead, which is what the active filter already reads.

do $$
begin
  if to_regclass('public.service_catalog_items') is null then
    raise exception 'service_catalog_items is missing; the published catalog cannot be synchronised';
  end if;
end
$$;

with published (service_key, product_key, name, summary, price_note, plan_floor, lifecycle_status, route_path, sort_order, entitlement_integration_verified, execution_enabled) as (
  values
  ('nexus-shared-operating-spine', 'sonara_industries', 'One Connected Account', 'Your workspaces, billing, requests and recent activity in one place across all three studios.', 'No charge.', 'free', 'beta', '/dashboard', 10, true, true),
  ('identity-organizations-access', 'sonara_industries', 'Logins, Team & Permissions', 'Sign-up, sign-in, your team, and who is allowed to do what in each workspace.', 'No charge.', 'free', 'active', '/account', 20, true, true),
  ('billing-entitlements', 'sonara_industries', 'Plans & Billing', 'Subscriptions, one-off purchases, and which features your plan opens up.', 'No charge.', 'free', 'beta', '/pricing', 30, true, true),
  ('asset-document-vault', 'sonara_industries', 'Your Records, And Taking Them With You', 'See every kind of record your account holds, download the lot, and ask for it to be erased.', 'No charge.', 'free', 'beta', '/account/data', 40, true, true),
  ('integration-hub', 'sonara_industries', 'Connected Accounts', 'Safe connections to payments, email, publishing, and analytics.', 'No charge.', 'free', 'beta', '/account/integrations', 50, true, true),
  ('audit-security-readiness-center', 'sonara_industries', 'Security & Status Center', 'One place to see permissions, records, connections, and admin activity across your account.', 'No charge.', 'free', 'beta', '/readiness', 60, true, true),
  ('market-intelligence-product-lifecycle', 'sonara_industries', 'Research & Roadmap', 'Dated competitor research, market signals, and the stop rules written down before anybody acts on them.', 'No charge.', 'free', 'active', '/market-intelligence', 70, true, true),
  ('business-readiness-plan', 'business_builder', 'Business Plan & Setup Check', 'An honest look at your business model, milestones, costs, risks, support, legal and security gaps, with a plan to close them.', 'No charge.', 'free', 'beta', '/business-builder/tools/readiness', 80, true, true),
  ('market-offer-pricing-lab', 'business_builder', 'Offer & Pricing Builder', 'Work out who you can realistically reach, then build the package, scope, costs, margin, proof, and price.', 'No charge.', 'free', 'active', '/business-builder/tools/offer', 90, true, true),
  ('customer-intake-service-crm', 'business_builder', 'Customer & Enquiry Tracker', 'Every prospect, enquiry, customer, permission, note, status, and next step in one list.', 'Included in Starter and above.', 'starter', 'active', '/business-builder/owner/customers', 100, true, true),
  ('quotes-billing-payments', 'business_builder', 'Quotes, Invoices & Getting Paid', 'Quotes, the invoices they turn into, what is on each one, what has been paid and what you are still owed.', 'Included in Core and above.', 'core', 'beta', '/business-builder/owner/invoices', 110, true, true),
  ('booking-operations-team', 'business_builder', 'Bookings, Staff & Day-to-Day', 'Appointments, staff, shifts, hours, stock, suppliers, locations, equipment, recipes, food costs, and reports.', 'Included in Core and above.', 'core', 'beta', '/business-builder/owner', 120, true, true),
  ('business-evidence-compliance-portability', 'business_builder', 'Records & Exports', 'Prepare your records for an accountant, see whether each export finished, and download everything on your account.', 'Included in Core and above.', 'core', 'beta', '/business-builder/owner/accounting-exports', 130, true, true),
  ('brand-asset-system', 'creator_studio', 'Brand & Asset Library', 'Every asset you have, with a note on where it came from and what you are allowed to do with it.', 'Included in Starter and above.', 'starter', 'beta', '/creator-studio/assets', 140, true, true),
  ('content-project-repurposing', 'creator_studio', 'Content Projects & Reuse', 'Briefs, tasks, files, revisions, approvals, deadlines, deliverables, and a version for each channel.', 'Included in Starter and above.', 'starter', 'beta', '/creator-studio/tools/brief', 150, true, true),
  ('release-package-builder', 'creator_studio', 'Release Packager', 'Files, details, credits, collaborators, rights, permissions, sources, calendar, checklist, and the handoff to distribution.', 'Included in Core and above.', 'core', 'beta', '/creator-studio/music-system', 160, true, true),
  ('creator-commerce-digital-products', 'creator_studio', 'Selling Your Work', 'Write down what you are selling, what is in it and what it costs, and keep the draft.', 'No charge.', 'free', 'beta', '/creator-studio/offers/free', 170, true, true),
  ('customer-timeline-consent-center', 'growth_studio', 'Customer History & Permissions', 'Merged leads, customers and fans, with every touchpoint, purchase, and the permission behind each one.', 'Included in Core and above.', 'core', 'beta', '/growth-studio/consent', 180, true, true),
  ('lead-capture-segments-crm', 'growth_studio', 'Lead Capture & Lists', 'Permission-aware forms, lead records, audience rules written in plain English, sources, status, and who to call first.', 'Included in Core and above.', 'core', 'beta', '/growth-studio/segments', 190, true, true),
  ('campaign-journey-builder', 'growth_studio', 'Campaign Builder', 'Goals, audience, offer, channels, content, owners, dates, approvals, triggers, steps, stop rules, and results.', 'Included in Core and above.', 'core', 'beta', '/growth-studio/your-campaigns', 200, true, true),
  ('landing-conversion-tracking', 'growth_studio', 'Landing Pages & Results', 'Your totals, and which campaign or source the sales you recorded actually came from.', 'Included in Core and above.', 'core', 'beta', '/growth-studio/attribution', 210, true, true),
  ('attribution-incrementality-lab', 'growth_studio', 'Did It Actually Work?', 'Written-down methods, how fresh the data is, how confident we are, duplicate handling, fair comparisons, and what the numbers cannot tell you.', 'Included in Pro.', 'pro', 'beta', '/growth-studio/experiments', 220, true, true),
  ('provider-diagnostics-answer-visibility', 'growth_studio', 'Connection Health', 'Which services you have connected, what each one is allowed to do, and what it has run.', 'Included in Pro.', 'pro', 'beta', '/growth-studio/providers', 230, true, true)
)
update public.service_catalog_items as target
set
  product_key = published.product_key,
  name = published.name,
  summary = published.summary,
  price_note = published.price_note,
  plan_floor = published.plan_floor,
  lifecycle_status = published.lifecycle_status,
  route_path = published.route_path,
  sort_order = published.sort_order,
  entitlement_integration_verified = published.entitlement_integration_verified,
  execution_enabled = published.execution_enabled,
  product_type = 'software_product',
  status = 'active',
  metadata = coalesce(target.metadata, '{}'::jsonb) || jsonb_build_object('catalogVersion', '2026-07-25')
from published
where target.service_key = published.service_key;

-- Retire the rows the catalog no longer lists.
--
-- /service-catalog filters on status = 'active', so this is the switch that
-- decides whether a product is published. The row and its history stay.
update public.service_catalog_items as target
set status = 'retired'
where target.status = 'active'
  and target.service_key is not null
  and target.service_key not in (
    'nexus-shared-operating-spine',
    'identity-organizations-access',
    'billing-entitlements',
    'asset-document-vault',
    'integration-hub',
    'audit-security-readiness-center',
    'market-intelligence-product-lifecycle',
    'business-readiness-plan',
    'market-offer-pricing-lab',
    'customer-intake-service-crm',
    'quotes-billing-payments',
    'booking-operations-team',
    'business-evidence-compliance-portability',
    'brand-asset-system',
    'content-project-repurposing',
    'release-package-builder',
    'creator-commerce-digital-products',
    'customer-timeline-consent-center',
    'lead-capture-segments-crm',
    'campaign-journey-builder',
    'landing-conversion-tracking',
    'attribution-incrementality-lab',
    'provider-diagnostics-answer-visibility'
  );

-- Every product in the code catalog must now be an active published row.
--
-- The retirement above cannot fail this check, because it only ever touches
-- keys the catalog does not list. What it catches is the other direction: a
-- product renamed in code without a matching service_key in the table, where
-- the update above silently matches nothing and the product never reaches the
-- published catalog at all. That is the failure the sync exists to prevent,
-- and until now nothing asserted it.
do $$
declare
  missing text;
begin
  select string_agg(published.service_key, ', ' order by published.service_key)
    into missing
  from (values
    ('nexus-shared-operating-spine'),
    ('identity-organizations-access'),
    ('billing-entitlements'),
    ('asset-document-vault'),
    ('integration-hub'),
    ('audit-security-readiness-center'),
    ('market-intelligence-product-lifecycle'),
    ('business-readiness-plan'),
    ('market-offer-pricing-lab'),
    ('customer-intake-service-crm'),
    ('quotes-billing-payments'),
    ('booking-operations-team'),
    ('business-evidence-compliance-portability'),
    ('brand-asset-system'),
    ('content-project-repurposing'),
    ('release-package-builder'),
    ('creator-commerce-digital-products'),
    ('customer-timeline-consent-center'),
    ('lead-capture-segments-crm'),
    ('campaign-journey-builder'),
    ('landing-conversion-tracking'),
    ('attribution-incrementality-lab'),
    ('provider-diagnostics-answer-visibility')
  ) as published(service_key)
  where not exists (
    select 1 from public.service_catalog_items
    where service_key = published.service_key and status = 'active'
  );

  if missing is not null then
    raise exception 'these catalog products have no active published row: %', missing;
  end if;
end
$$;

-- The retired name must not survive anywhere in the published catalog. This is
-- the check, not a comment: if a row still carries it the migration fails
-- rather than letting production keep serving it.
do $$
declare
  offending integer;
begin
  select count(*) into offending
  from public.service_catalog_items
  where name ilike '%nexus%' or summary ilike '%nexus%';

  if offending > 0 then
    raise exception 'a retired public name survives in service_catalog_items on % row(s)', offending;
  end if;
end
$$;
