-- Seed runtime definitions so saved results satisfy their formula-key foreign key.
-- No new tables, grants or customer records. Existing definitions are preserved.
INSERT INTO public.sonara_formula_definitions
  (formula_key,group_key,product_area,label,public_label,expression_text,required_inputs,target_tables,output_unit,role_visibility,status,notes)
VALUES
  ('expected_loss','operating_twin','Business Builder','Scenario expected loss','Scenario expected loss','event_probability * loss_amount','["event_probability","loss_amount"]','[]','money','["owner","admin"]','active','Bounded deterministic planning formula. See runtime input validation and market-focus research report for assumptions.'),
  ('smoothed_demand_level','inventory_operations','Business Builder','Smoothed demand level','Smoothed demand level','alpha * observed_demand + (1 - alpha) * previous_level','["alpha","observed_demand","previous_level"]','[]','quantity','["owner","admin"]','active','Bounded deterministic planning formula. See runtime input validation and market-focus research report for assumptions.'),
  ('service_capacity_jobs','inventory_operations','Business Builder','Service capacity','Service capacity','floor(available_minutes / minutes_per_job)','["available_minutes","minutes_per_job"]','[]','jobs','["owner","admin"]','active','Bounded deterministic planning formula. See runtime input validation and market-focus research report for assumptions.'),
  ('media_duration_seconds','creator_music','Creator Studio','Frame duration','Frame duration','frame_count / frames_per_second','["frame_count","frames_per_second"]','[]','seconds','["owner","admin"]','active','Bounded deterministic planning formula. See runtime input validation and market-focus research report for assumptions.'),
  ('media_payload_mebibytes','creator_music','Creator Studio','Estimated media payload','Estimated media payload','bitrate_bits_per_second * duration_seconds / (8 * 1048576)','["bitrate_bits_per_second","duration_seconds"]','[]','MiB','["owner","admin"]','active','Bounded deterministic planning formula. See runtime input validation and market-focus research report for assumptions.'),
  ('tracked_motion_speed','creator_music','Creator Studio','Calibrated motion speed','Calibrated motion speed','displacement_meters / elapsed_seconds','["displacement_meters","elapsed_seconds"]','[]','meters_per_second','["owner","admin"]','active','Bounded deterministic planning formula. See runtime input validation and market-focus research report for assumptions.'),
  ('kinetic_energy_joules','operating_twin','Business Builder','Translational kinetic energy','Translational kinetic energy','mass_kg * speed_meters_per_second^2 / 2','["mass_kg","speed_meters_per_second"]','[]','joules','["owner","admin"]','active','SI kilograms and meters/second; translational, nonrelativistic energy. Not collision safety certification.'),
  ('dilution_stock_volume','operating_twin','Business Builder','Research dilution volume','Research dilution volume','target_concentration * final_volume / stock_concentration','["target_concentration","final_volume","stock_concentration"]','[]','input_volume_unit','["owner","admin"]','active','Same concentration units and same volume units. Target cannot exceed stock. Research planning only, not clinical dosing.'),
  ('render_time_estimate_seconds','creator_music','Creator Studio','Measured render time estimate','Measured render time estimate','frame_count / measured_frames_per_second + overhead_seconds','["frame_count","measured_frames_per_second","overhead_seconds"]','[]','seconds','["owner","admin"]','active','Measured throughput for comparable workload/hardware; constant average throughput and explicit overhead. Estimate, not SLA.'),
  ('uncompressed_image_bytes','creator_music','Creator Studio','Uncompressed image payload','Uncompressed image payload','width_pixels * height_pixels * channels * bytes_per_channel','["width_pixels","height_pixels","channels","bytes_per_channel"]','[]','bytes','["owner","admin"]','active','Packed samples only, not peak process/GPU memory; dimensions 1..8192, channels 1..4, bytes/channel 1..8.'),
  ('average_acceleration','creator_music','Creator Studio','Calibrated average acceleration','Calibrated average acceleration','(final_velocity - initial_velocity) / elapsed_seconds','["final_velocity","initial_velocity","elapsed_seconds"]','[]','meters_per_second_squared','["owner","admin"]','active','Calibrated signed velocities in meters/second and positive seconds. Interval average, not pose estimation.'),
  ('rectangle_area_square_meters','operating_twin','Business Builder','Rectangular surface area','Rectangular surface area','length_meters * width_meters','["length_meters","width_meters"]','[]','square_meters','["owner","admin"]','active','Nonnegative rectangular dimensions in meters. Not CAD geometry/import/export.')
ON CONFLICT (formula_key) DO NOTHING;
