-- Bring the published catalog rows in line with the catalog in code.
--
-- GENERATED by scripts/generate-catalog-sync-migration.cjs -- regenerate rather
-- than edit by hand.
--
-- /service-catalog merges service_catalog_items over the defaults in
-- lib/catalog/*.cjs, so the table wins wherever it holds a value. When the
-- product names were rewritten for customers, the table was left holding the
-- old ones -- including "SONARA Nexus Shared Operating Spine", a retired
-- public name AGENTS.md does not allow in active UI.
--
-- It also broke the production deploy: verify-production-product-catalog.mjs
-- compares these rows against the code and gates the release on them matching.
--
-- Updates only. No row is inserted or deleted here: every service_key below was
-- seeded by 20260725180000_recommended_product_catalog.sql, and a service_key
-- that is no longer present simply matches nothing.

do $$
begin
  if to_regclass('public.service_catalog_items') is null then
    raise exception 'service_catalog_items is missing; the published catalog cannot be synchronised';
  end if;
end
$$;

with published (service_key, product_key, name, summary, price_note, plan_floor, lifecycle_status, route_path, sort_order, entitlement_integration_verified, execution_enabled) as (
  values
  ('nexus-shared-operating-spine', 'sonara_industries', 'One Connected Account', 'Your customers, files, billing, and history stay in one place across all three studios.', 'Included in Core and above.', 'core', 'beta', '/products', 10, false, false),
  ('identity-organizations-access', 'sonara_industries', 'Logins, Team & Permissions', 'Sign-up, sign-in, your team, and who is allowed to do what in each workspace.', 'No charge.', 'free', 'active', '/account/setup', 20, true, true),
  ('billing-entitlements', 'sonara_industries', 'Plans & Billing', 'Subscriptions, one-off purchases, and which features your plan opens up.', 'Included in Starter and above.', 'starter', 'beta', '/pricing', 30, false, false),
  ('customer-consent-evidence-timeline', 'sonara_industries', 'Customer History', 'Every customer, permission, purchase, file, and result kept together in one timeline you own.', 'Included in Core and above.', 'core', 'validation_required', '/market-intelligence', 40, false, false),
  ('asset-document-vault', 'sonara_industries', 'File Storage', 'Private storage for documents, media, exports, and approvals, organised by the work that produced them.', 'Included in Starter and above.', 'starter', 'beta', '/dashboard', 50, false, false),
  ('integration-hub', 'sonara_industries', 'Connected Accounts', 'Safe connections to payments, email, publishing, file storage, and analytics.', 'Included in Core and above.', 'core', 'beta', '/account/integrations', 60, false, false),
  ('automation-approval-center', 'sonara_industries', 'Automations & Approvals', 'Repeatable tasks that run on your say-so, with retries and a record of what happened.', 'Included in Core and above.', 'core', 'beta', '/admin/ecosystem', 70, false, false),
  ('usage-cost-value-scorecards', 'sonara_industries', 'Cost & Value Reports', 'See what each tool costs to run, what it brings back, and which work is worth repeating.', 'Included in Pro.', 'pro', 'validation_required', '/admin/system', 80, false, false),
  ('audit-security-readiness-center', 'sonara_industries', 'Security & Status Center', 'One place to see permissions, records, connections, and admin activity across your account.', 'Included in Pro.', 'pro', 'beta', '/readiness', 90, false, false),
  ('market-intelligence-product-lifecycle', 'sonara_industries', 'Research & Roadmap', 'Dated research, scored opportunities, live experiments, the numbers behind them, and honest stop rules.', 'Included in Pro.', 'pro', 'active', '/market-intelligence', 100, false, false),
  ('first-transaction-mode', 'business_builder', 'Your First Sale, Step by Step', 'A guided path from your offer, to the enquiry, to the booking or order, to getting paid, to delivery and a review request.', 'Included in Starter and above.', 'starter', 'validation_required', '/business-builder', 110, true, false),
  ('business-readiness-plan', 'business_builder', 'Business Plan & Setup Check', 'An honest look at your business model, milestones, costs, risks, support, legal and security gaps, with a plan to close them.', 'No charge.', 'free', 'beta', '/business-builder/tools/readiness', 120, true, true),
  ('market-offer-pricing-lab', 'business_builder', 'Offer & Pricing Builder', 'Work out who you can realistically reach, then build the package, scope, costs, margin, proof, and price.', 'No charge.', 'free', 'active', '/business-builder/tools/offer', 130, true, true),
  ('customer-intake-service-crm', 'business_builder', 'Customer & Enquiry Tracker', 'Every prospect, enquiry, customer, permission, note, status, and next step in one list.', 'Included in Starter and above.', 'starter', 'active', '/business-builder/dashboard', 140, true, true),
  ('quotes-billing-payments', 'business_builder', 'Quotes, Invoices & Getting Paid', 'Quotes, invoice records, payment links, payment status, and the handoff back to your customer.', 'Included in Core and above.', 'core', 'beta', '/business-builder/billing', 150, true, true),
  ('booking-operations-team', 'business_builder', 'Bookings, Staff & Day-to-Day', 'Appointments, staff, shifts, hours, stock, suppliers, locations, equipment, recipes, food costs, and reports.', 'Included in Core and above.', 'core', 'beta', '/business-builder/dashboard', 160, true, true),
  ('vertical-starter-packs', 'business_builder', 'Ready-Made Starter Packs', 'Pre-built setups for service businesses, food and mobile vendors, consultants, and creator-led services.', 'Included in Starter and above.', 'starter', 'validation_required', '/business-builder', 170, true, false),
  ('business-evidence-compliance-portability', 'business_builder', 'Records, Renewals & Exports', 'A document vault, renewal reminders, imports, exports, approvals, and proof of what you own.', 'Included in Core and above.', 'core', 'validation_required', '/business-builder/launch-readiness', 180, true, false),
  ('brand-asset-system', 'creator_studio', 'Brand & Asset Library', 'Your identity, brand kit, files, versions, sources, ownership notes, licences, and approvals in one library.', 'Included in Starter and above.', 'starter', 'beta', '/creator-studio/dashboard', 190, true, true),
  ('content-project-repurposing', 'creator_studio', 'Content Projects & Reuse', 'Briefs, tasks, files, revisions, approvals, deadlines, deliverables, and a version for each channel.', 'Included in Starter and above.', 'starter', 'beta', '/creator-studio/tools/brief', 200, true, true),
  ('release-package-builder', 'creator_studio', 'Release Packager', 'Files, details, credits, collaborators, rights, permissions, sources, calendar, checklist, and the handoff to distribution.', 'Included in Core and above.', 'core', 'beta', '/creator-studio/music-system', 210, true, true),
  ('rights-originality-collaborators', 'creator_studio', 'Credits, Splits & Rights', 'Contributors, splits, references, tools used, changes made, originality checks, likeness limits, and approvals.', 'Included in Core and above.', 'core', 'validation_required', '/creator-studio', 220, true, false),
  ('creator-commerce-digital-products', 'creator_studio', 'Selling Your Work', 'Products, services, licences, bundles, prices, delivery files, payment links, and your refund position.', 'Included in Starter and above.', 'starter', 'beta', '/creator-studio/launch-readiness', 230, true, true),
  ('fan-buyer-partner-crm', 'creator_studio', 'Your Audience List', 'Fans, buyers, clients, collaborators, supporters, and brand partners, with permissions and opt-outs, owned by you.', 'Included in Core and above.', 'core', 'validation_required', '/creator-studio/dashboard', 240, true, false),
  ('brand-deal-operations', 'creator_studio', 'Brand Deals', 'Briefs, deliverables, revisions, approvals, disclosures, rights, payment status, and the results you report back.', 'Included in Pro.', 'pro', 'validation_required', '/creator-studio', 250, true, false),
  ('creator-export-revenue-intelligence', 'creator_studio', 'Exports & Earnings', 'Take your work with you, and see sales, services, memberships, partnerships, campaign results, costs, and what is left over.', 'Included in Pro.', 'pro', 'validation_required', '/creator-studio/dashboard', 260, true, false),
  ('customer-timeline-consent-center', 'growth_studio', 'Customer History & Permissions', 'Merged leads, customers and fans, with every touchpoint, purchase, and the permission behind each one.', 'Included in Core and above.', 'core', 'validation_required', '/growth-studio/consent', 270, true, false),
  ('lead-capture-segments-crm', 'growth_studio', 'Lead Capture & Lists', 'Permission-aware forms, lead records, audience rules written in plain English, sources, status, and who to call first.', 'Included in Starter and above.', 'starter', 'beta', '/growth-studio/segments', 280, true, true),
  ('campaign-journey-builder', 'growth_studio', 'Campaign Builder', 'Goals, audience, offer, channels, content, owners, dates, approvals, triggers, steps, stop rules, and results.', 'Included in Core and above.', 'core', 'validation_required', '/growth-studio/dashboard', 290, true, false),
  ('lifecycle-messaging-social-planning', 'growth_studio', 'Follow-Up & Social Planning', 'Welcome messages, follow-ups, win-backs, review and referral asks, and social content, ready to hand to your sending tool.', 'Included in Core and above.', 'core', 'planned', '/growth-studio', 300, true, false),
  ('landing-conversion-tracking', 'growth_studio', 'Landing Pages & Results', 'Link your message, offer, page, form, booking or payment, campaign tag, and the sales that came from it.', 'Included in Starter and above.', 'starter', 'beta', '/growth-studio/attribution', 310, true, true),
  ('attribution-incrementality-lab', 'growth_studio', 'Did It Actually Work?', 'Written-down methods, how fresh the data is, how confident we are, duplicate handling, fair comparisons, and what the numbers cannot tell you.', 'Included in Pro.', 'pro', 'validation_required', '/growth-studio/experiments', 320, true, false),
  ('reviews-referrals-partnerships', 'growth_studio', 'Reviews, Referrals & Partners', 'Honest review requests, referral offers, creator partnerships, disclosures, deliverables, costs, and outcomes.', 'Included in Pro.', 'pro', 'validation_required', '/growth-studio', 330, true, false),
  ('provider-diagnostics-answer-visibility', 'growth_studio', 'Connection Health', 'Which connections are working, what they are allowed to do, limits, jobs, errors, retries, costs, approvals, and where you are being mentioned.', 'Included in Pro.', 'pro', 'beta', '/growth-studio/providers', 340, true, true)
)
update public.service_catalog_items as target
set
  product_key = published.product_key,
  name = published.name,
  summary = published.summary,
  price_note = published.price_note,
  plan_floor = published.plan_floor,
  lifecycle_status = published.lifecycle_status,
  route_path = published.route_path,
  sort_order = published.sort_order,
  entitlement_integration_verified = published.entitlement_integration_verified,
  execution_enabled = published.execution_enabled,
  product_type = 'software_product',
  status = 'active',
  metadata = coalesce(target.metadata, '{}'::jsonb) || jsonb_build_object('catalogVersion', '2026-07-25')
from published
where target.service_key = published.service_key;

-- The retired name must not survive anywhere in the published catalog. This is
-- the check, not a comment: if a row still carries it the migration fails
-- rather than letting production keep serving it.
do $$
declare
  offending integer;
begin
  select count(*) into offending
  from public.service_catalog_items
  where name ilike '%nexus%' or summary ilike '%nexus%';

  if offending > 0 then
    raise exception 'a retired public name survives in service_catalog_items on % row(s)', offending;
  end if;
end
$$;
