-- The published catalog is complete, and carries no retired name.
--
-- GENERATED by scripts/generate-catalog-sync-migration.cjs -- regenerate rather
-- than edit by hand.
--
-- These two checks used to live at the end of
-- 20260812120000_retire_removed_catalog_products.sql. They were generated from
-- the current catalog and written into a migration dated six days before
-- nineteen of those products were inserted, so a fresh replay of the migration
-- history always failed on the first of them. Production never noticed: it
-- migrated forward in real time and never re-ran the old file.
--
-- An operation belongs where it happened. An assertion about the end state
-- belongs at the end. That is the whole reason this file exists.

do $$
begin
  if to_regclass('public.service_catalog_items') is null then
    raise exception 'service_catalog_items is missing; the published catalog cannot be checked';
  end if;
end
$$;

-- Every product in the code catalog must be an active published row.
--
-- The retirement in 20260812120000 cannot fail this, because it only ever
-- touches keys the catalog does not list. What this catches is the other
-- direction: a product renamed in code without a matching service_key in the
-- table, where the sync update silently matches nothing and the product never
-- reaches the published catalog at all.
do $$
declare
  missing text;
begin
  select string_agg(published.service_key, ', ' order by published.service_key)
    into missing
  from (values
    ('nexus-shared-operating-spine'),
    ('identity-organizations-access'),
    ('billing-entitlements'),
    ('asset-document-vault'),
    ('integration-hub'),
    ('audit-security-readiness-center'),
    ('market-intelligence-product-lifecycle'),
    ('business-readiness-plan'),
    ('market-offer-pricing-lab'),
    ('customer-intake-service-crm'),
    ('quotes-billing-payments'),
    ('booking-operations-team'),
    ('business-evidence-compliance-portability'),
    ('break-even-runway-planner'),
    ('shift-rota-cost-planner'),
    ('deposit-payment-schedule'),
    ('price-rise-planner'),
    ('software-spend-auditor'),
    ('quiet-month-cash-plan'),
    ('brand-asset-system'),
    ('content-project-repurposing'),
    ('release-package-builder'),
    ('creator-commerce-digital-products'),
    ('creator-rate-card-builder'),
    ('split-sheet-and-credits'),
    ('content-repurposing-planner'),
    ('deal-memo-recorder'),
    ('late-payment-escalation'),
    ('usage-rights-expiry'),
    ('storyboard-builder'),
    ('customer-timeline-consent-center'),
    ('lead-capture-segments-crm'),
    ('campaign-journey-builder'),
    ('landing-conversion-tracking'),
    ('attribution-incrementality-lab'),
    ('provider-diagnostics-answer-visibility'),
    ('campaign-budget-split'),
    ('referral-reward-planner'),
    ('follow-up-schedule-planner'),
    ('referral-source-tracker'),
    ('review-recency-score'),
    ('enquiry-response-clock')
  ) as published(service_key)
  where not exists (
    select 1 from public.service_catalog_items
    where service_key = published.service_key and status = 'active'
  );

  if missing is not null then
    raise exception 'these catalog products have no active published row: %', missing;
  end if;
end
$$;

-- The retired name must not survive anywhere in the published catalog. This is
-- the check, not a comment: if a row still carries it the migration fails
-- rather than letting production keep serving it.
--
-- Stronger here than it was at 20260812120000, and that is a second reason for
-- the move: there it only ever saw the rows that existed on 12 August, so a
-- retired name introduced by any later migration went unchecked.
do $$
declare
  offending integer;
begin
  select count(*) into offending
  from public.service_catalog_items
  where name ilike '%nexus%' or summary ilike '%nexus%';

  if offending > 0 then
    raise exception 'a retired public name survives in service_catalog_items on % row(s)', offending;
  end if;
end
$$;
