-- Generated by scripts/generate-existing-table-shape-repair.cjs. Do not edit by hand.
--
-- The other half of 20260811210000_repair_missing_platform_tables.sql.
--
-- That migration is 42 `create table if not exists` statements, which repair a
-- table that is ABSENT and do nothing for a table that is PRESENT in an older
-- shape. Production is in the second state. Deployment run #125 on 3 September
-- 2026 failed on exactly that:
--
--     Applying migration 20260819030000_member_read_policies_research_sources.sql...
--     NOTICE: skipping shared_links: table not present
--     ERROR: column "organization_id" does not exist (SQLSTATE 42703)
--
-- `shared_links` was absent, so its guard skipped it. `customers` was present
-- without `organization_id`, so the guard let it through and the policy failed.
--
-- Every statement below is `add column if not exists`, under a `to_regclass`
-- guard, so this is idempotent and a table it does not find is a notice rather
-- than a failed deployment. Replayed against an empty database every statement
-- is a no-op, because the migration one version earlier creates each table whole.
--
-- Columns are added NULLABLE and without their primary key, unique or foreign
-- key clauses -- a table that already holds rows cannot take those. So this
-- gives production the columns later migrations need and NOT full referential
-- parity with a fresh replay. That divergence is real and is stated rather than
-- hidden; closing it needs a dump of what production actually holds. The last
-- time this was guessed at, the guess was that creating absent tables would be
-- enough.
--
-- 42 tables, 530 column repairs.

do $$
begin
  if to_regclass('public.organizations') is null then
    raise notice 'skipping organizations: table not present';
    return;
  end if;

    execute 'alter table public.organizations add column if not exists name text';
    execute 'alter table public.organizations add column if not exists created_by uuid';
    execute 'alter table public.organizations add column if not exists created_at timestamptz default now()';
    execute 'alter table public.organizations add column if not exists updated_at timestamptz default now()';
    execute 'alter table public.organizations add column if not exists metadata jsonb default ''{}''::jsonb';
end
$$;

do $$
begin
  if to_regclass('public.profiles') is null then
    raise notice 'skipping profiles: table not present';
    return;
  end if;

    execute 'alter table public.profiles add column if not exists full_name text';
    execute 'alter table public.profiles add column if not exists email text';
    execute 'alter table public.profiles add column if not exists created_at timestamptz default now()';
    execute 'alter table public.profiles add column if not exists updated_at timestamptz default now()';
    execute 'alter table public.profiles add column if not exists metadata jsonb default ''{}''::jsonb';
end
$$;

do $$
begin
  if to_regclass('public.sonara_platforms') is null then
    raise notice 'skipping sonara_platforms: table not present';
    return;
  end if;

    execute 'alter table public.sonara_platforms add column if not exists organization_id uuid';
    execute 'alter table public.sonara_platforms add column if not exists user_id uuid';
    execute 'alter table public.sonara_platforms add column if not exists company_key text';
    execute 'alter table public.sonara_platforms add column if not exists product_key text';
    execute 'alter table public.sonara_platforms add column if not exists name text';
    execute 'alter table public.sonara_platforms add column if not exists slug text';
    execute 'alter table public.sonara_platforms add column if not exists platform_type text default ''custom''';
    execute 'alter table public.sonara_platforms add column if not exists description text';
    execute 'alter table public.sonara_platforms add column if not exists status text default ''draft''';
    execute 'alter table public.sonara_platforms add column if not exists theme jsonb default ''{}''::jsonb';
    execute 'alter table public.sonara_platforms add column if not exists settings jsonb default ''{}''::jsonb';
    execute 'alter table public.sonara_platforms add column if not exists created_at timestamptz default now() default now()';
    execute 'alter table public.sonara_platforms add column if not exists updated_at timestamptz default now() default now()';
end
$$;

do $$
begin
  if to_regclass('public.customer_records') is null then
    raise notice 'skipping customer_records: table not present';
    return;
  end if;

    execute 'alter table public.customer_records add column if not exists organization_id uuid';
    execute 'alter table public.customer_records add column if not exists user_id uuid';
    execute 'alter table public.customer_records add column if not exists platform_id uuid';
    execute 'alter table public.customer_records add column if not exists name text';
    execute 'alter table public.customer_records add column if not exists email text';
    execute 'alter table public.customer_records add column if not exists phone text';
    execute 'alter table public.customer_records add column if not exists status text default ''lead''';
    execute 'alter table public.customer_records add column if not exists notes text';
    execute 'alter table public.customer_records add column if not exists metadata jsonb default ''{}''::jsonb';
    execute 'alter table public.customer_records add column if not exists created_at timestamptz default now() default now()';
    execute 'alter table public.customer_records add column if not exists updated_at timestamptz default now() default now()';
end
$$;

do $$
begin
  if to_regclass('public.growth_campaigns') is null then
    raise notice 'skipping growth_campaigns: table not present';
    return;
  end if;

    execute 'alter table public.growth_campaigns add column if not exists organization_id uuid';
    execute 'alter table public.growth_campaigns add column if not exists user_id uuid';
    execute 'alter table public.growth_campaigns add column if not exists platform_id uuid';
    execute 'alter table public.growth_campaigns add column if not exists name text';
    execute 'alter table public.growth_campaigns add column if not exists goal text';
    execute 'alter table public.growth_campaigns add column if not exists channel text';
    execute 'alter table public.growth_campaigns add column if not exists status text default ''draft''';
    execute 'alter table public.growth_campaigns add column if not exists metadata jsonb default ''{}''::jsonb';
    execute 'alter table public.growth_campaigns add column if not exists created_at timestamptz default now() default now()';
    execute 'alter table public.growth_campaigns add column if not exists updated_at timestamptz default now() default now()';
end
$$;

do $$
begin
  if to_regclass('public.growth_leads') is null then
    raise notice 'skipping growth_leads: table not present';
    return;
  end if;

    execute 'alter table public.growth_leads add column if not exists organization_id uuid';
    execute 'alter table public.growth_leads add column if not exists user_id uuid';
    execute 'alter table public.growth_leads add column if not exists platform_id uuid';
    execute 'alter table public.growth_leads add column if not exists campaign_id uuid';
    execute 'alter table public.growth_leads add column if not exists name text';
    execute 'alter table public.growth_leads add column if not exists email text';
    execute 'alter table public.growth_leads add column if not exists phone text';
    execute 'alter table public.growth_leads add column if not exists source text';
    execute 'alter table public.growth_leads add column if not exists status text default ''new''';
    execute 'alter table public.growth_leads add column if not exists metadata jsonb default ''{}''::jsonb';
    execute 'alter table public.growth_leads add column if not exists created_at timestamptz default now() default now()';
    execute 'alter table public.growth_leads add column if not exists updated_at timestamptz default now() default now()';
end
$$;

do $$
begin
  if to_regclass('public.growth_experiments') is null then
    raise notice 'skipping growth_experiments: table not present';
    return;
  end if;

    execute 'alter table public.growth_experiments add column if not exists organization_id uuid';
    execute 'alter table public.growth_experiments add column if not exists user_id uuid';
    execute 'alter table public.growth_experiments add column if not exists platform_id uuid';
    execute 'alter table public.growth_experiments add column if not exists campaign_id uuid';
    execute 'alter table public.growth_experiments add column if not exists name text';
    execute 'alter table public.growth_experiments add column if not exists hypothesis text';
    execute 'alter table public.growth_experiments add column if not exists result text';
    execute 'alter table public.growth_experiments add column if not exists status text default ''planned''';
    execute 'alter table public.growth_experiments add column if not exists metadata jsonb default ''{}''::jsonb';
    execute 'alter table public.growth_experiments add column if not exists created_at timestamptz default now() default now()';
    execute 'alter table public.growth_experiments add column if not exists updated_at timestamptz default now() default now()';
end
$$;

do $$
begin
  if to_regclass('public.automation_rules') is null then
    raise notice 'skipping automation_rules: table not present';
    return;
  end if;

    execute 'alter table public.automation_rules add column if not exists organization_id uuid';
    execute 'alter table public.automation_rules add column if not exists user_id uuid';
    execute 'alter table public.automation_rules add column if not exists platform_id uuid';
    execute 'alter table public.automation_rules add column if not exists name text';
    execute 'alter table public.automation_rules add column if not exists trigger_key text';
    execute 'alter table public.automation_rules add column if not exists action_key text';
    execute 'alter table public.automation_rules add column if not exists status text default ''disabled''';
    execute 'alter table public.automation_rules add column if not exists config jsonb default ''{}''::jsonb';
    execute 'alter table public.automation_rules add column if not exists created_at timestamptz default now() default now()';
    execute 'alter table public.automation_rules add column if not exists updated_at timestamptz default now() default now()';
end
$$;

do $$
begin
  if to_regclass('public.business_locations') is null then
    raise notice 'skipping business_locations: table not present';
    return;
  end if;

    execute 'alter table public.business_locations add column if not exists organization_id uuid';
    execute 'alter table public.business_locations add column if not exists platform_id uuid';
    execute 'alter table public.business_locations add column if not exists name text';
    execute 'alter table public.business_locations add column if not exists location_type text default ''storefront''';
    execute 'alter table public.business_locations add column if not exists address_line1 text';
    execute 'alter table public.business_locations add column if not exists address_line2 text';
    execute 'alter table public.business_locations add column if not exists city text';
    execute 'alter table public.business_locations add column if not exists region text';
    execute 'alter table public.business_locations add column if not exists postal_code text';
    execute 'alter table public.business_locations add column if not exists country text default ''US'' default ''US''';
    execute 'alter table public.business_locations add column if not exists phone text';
    execute 'alter table public.business_locations add column if not exists email text';
    execute 'alter table public.business_locations add column if not exists status text default ''active''';
    execute 'alter table public.business_locations add column if not exists metadata jsonb default ''{}''::jsonb';
    execute 'alter table public.business_locations add column if not exists created_at timestamptz default now() default now()';
    execute 'alter table public.business_locations add column if not exists updated_at timestamptz default now() default now()';
end
$$;

do $$
begin
  if to_regclass('public.business_service_catalog') is null then
    raise notice 'skipping business_service_catalog: table not present';
    return;
  end if;

    execute 'alter table public.business_service_catalog add column if not exists organization_id uuid';
    execute 'alter table public.business_service_catalog add column if not exists platform_id uuid';
    execute 'alter table public.business_service_catalog add column if not exists location_id uuid';
    execute 'alter table public.business_service_catalog add column if not exists name text';
    execute 'alter table public.business_service_catalog add column if not exists category text';
    execute 'alter table public.business_service_catalog add column if not exists description text';
    execute 'alter table public.business_service_catalog add column if not exists price_cents integer default 0 default 0';
    execute 'alter table public.business_service_catalog add column if not exists currency text default ''usd'' default ''usd''';
    execute 'alter table public.business_service_catalog add column if not exists duration_minutes integer';
    execute 'alter table public.business_service_catalog add column if not exists status text default ''active''';
    execute 'alter table public.business_service_catalog add column if not exists metadata jsonb default ''{}''::jsonb';
    execute 'alter table public.business_service_catalog add column if not exists created_at timestamptz default now() default now()';
    execute 'alter table public.business_service_catalog add column if not exists updated_at timestamptz default now() default now()';
end
$$;

do $$
begin
  if to_regclass('public.business_bookings') is null then
    raise notice 'skipping business_bookings: table not present';
    return;
  end if;

    execute 'alter table public.business_bookings add column if not exists organization_id uuid';
    execute 'alter table public.business_bookings add column if not exists platform_id uuid';
    execute 'alter table public.business_bookings add column if not exists location_id uuid';
    execute 'alter table public.business_bookings add column if not exists service_id uuid';
    execute 'alter table public.business_bookings add column if not exists customer_id uuid';
    execute 'alter table public.business_bookings add column if not exists assigned_employee_id uuid';
    execute 'alter table public.business_bookings add column if not exists customer_name text';
    execute 'alter table public.business_bookings add column if not exists customer_email text';
    execute 'alter table public.business_bookings add column if not exists customer_phone text';
    execute 'alter table public.business_bookings add column if not exists starts_at timestamptz';
    execute 'alter table public.business_bookings add column if not exists ends_at timestamptz';
    execute 'alter table public.business_bookings add column if not exists status text default ''requested''';
    execute 'alter table public.business_bookings add column if not exists notes text';
    execute 'alter table public.business_bookings add column if not exists metadata jsonb default ''{}''::jsonb';
    execute 'alter table public.business_bookings add column if not exists created_at timestamptz default now() default now()';
    execute 'alter table public.business_bookings add column if not exists updated_at timestamptz default now() default now()';
end
$$;

do $$
begin
  if to_regclass('public.business_employee_profiles') is null then
    raise notice 'skipping business_employee_profiles: table not present';
    return;
  end if;

    execute 'alter table public.business_employee_profiles add column if not exists organization_id uuid';
    execute 'alter table public.business_employee_profiles add column if not exists user_id uuid';
    execute 'alter table public.business_employee_profiles add column if not exists location_id uuid';
    execute 'alter table public.business_employee_profiles add column if not exists employee_number text';
    execute 'alter table public.business_employee_profiles add column if not exists display_name text';
    execute 'alter table public.business_employee_profiles add column if not exists email text';
    execute 'alter table public.business_employee_profiles add column if not exists phone text';
    execute 'alter table public.business_employee_profiles add column if not exists job_title text';
    execute 'alter table public.business_employee_profiles add column if not exists employment_type text default ''employee''';
    execute 'alter table public.business_employee_profiles add column if not exists status text default ''active''';
    execute 'alter table public.business_employee_profiles add column if not exists hire_date date';
    execute 'alter table public.business_employee_profiles add column if not exists emergency_contact jsonb default ''{}''::jsonb';
    execute 'alter table public.business_employee_profiles add column if not exists metadata jsonb default ''{}''::jsonb';
    execute 'alter table public.business_employee_profiles add column if not exists created_at timestamptz default now() default now()';
    execute 'alter table public.business_employee_profiles add column if not exists updated_at timestamptz default now() default now()';
end
$$;

do $$
begin
  if to_regclass('public.employee_schedules') is null then
    raise notice 'skipping employee_schedules: table not present';
    return;
  end if;

    execute 'alter table public.employee_schedules add column if not exists organization_id uuid';
    execute 'alter table public.employee_schedules add column if not exists employee_id uuid';
    execute 'alter table public.employee_schedules add column if not exists location_id uuid';
    execute 'alter table public.employee_schedules add column if not exists role_label text';
    execute 'alter table public.employee_schedules add column if not exists starts_at timestamptz';
    execute 'alter table public.employee_schedules add column if not exists ends_at timestamptz';
    execute 'alter table public.employee_schedules add column if not exists status text default ''scheduled''';
    execute 'alter table public.employee_schedules add column if not exists notes text';
    execute 'alter table public.employee_schedules add column if not exists created_at timestamptz default now() default now()';
    execute 'alter table public.employee_schedules add column if not exists updated_at timestamptz default now() default now()';
end
$$;

do $$
begin
  if to_regclass('public.employee_time_entries') is null then
    raise notice 'skipping employee_time_entries: table not present';
    return;
  end if;

    execute 'alter table public.employee_time_entries add column if not exists organization_id uuid';
    execute 'alter table public.employee_time_entries add column if not exists employee_id uuid';
    execute 'alter table public.employee_time_entries add column if not exists location_id uuid';
    execute 'alter table public.employee_time_entries add column if not exists clock_in_at timestamptz';
    execute 'alter table public.employee_time_entries add column if not exists clock_out_at timestamptz';
    execute 'alter table public.employee_time_entries add column if not exists break_minutes integer default 0 default 0';
    execute 'alter table public.employee_time_entries add column if not exists entry_source text default ''employee_portal''';
    execute 'alter table public.employee_time_entries add column if not exists status text default ''open''';
    execute 'alter table public.employee_time_entries add column if not exists approved_by uuid';
    execute 'alter table public.employee_time_entries add column if not exists approved_at timestamptz';
    execute 'alter table public.employee_time_entries add column if not exists notes text';
    execute 'alter table public.employee_time_entries add column if not exists metadata jsonb default ''{}''::jsonb';
    execute 'alter table public.employee_time_entries add column if not exists created_at timestamptz default now() default now()';
    execute 'alter table public.employee_time_entries add column if not exists updated_at timestamptz default now() default now()';
end
$$;

do $$
begin
  if to_regclass('public.employee_announcements') is null then
    raise notice 'skipping employee_announcements: table not present';
    return;
  end if;

    execute 'alter table public.employee_announcements add column if not exists organization_id uuid';
    execute 'alter table public.employee_announcements add column if not exists location_id uuid';
    execute 'alter table public.employee_announcements add column if not exists created_by uuid';
    execute 'alter table public.employee_announcements add column if not exists title text';
    execute 'alter table public.employee_announcements add column if not exists message text';
    execute 'alter table public.employee_announcements add column if not exists audience text default ''all''';
    execute 'alter table public.employee_announcements add column if not exists status text default ''published''';
    execute 'alter table public.employee_announcements add column if not exists published_at timestamptz default now() default now()';
    execute 'alter table public.employee_announcements add column if not exists created_at timestamptz default now() default now()';
    execute 'alter table public.employee_announcements add column if not exists updated_at timestamptz default now() default now()';
end
$$;

do $$
begin
  if to_regclass('public.employee_tasks') is null then
    raise notice 'skipping employee_tasks: table not present';
    return;
  end if;

    execute 'alter table public.employee_tasks add column if not exists organization_id uuid';
    execute 'alter table public.employee_tasks add column if not exists assigned_employee_id uuid';
    execute 'alter table public.employee_tasks add column if not exists created_by uuid';
    execute 'alter table public.employee_tasks add column if not exists title text';
    execute 'alter table public.employee_tasks add column if not exists description text';
    execute 'alter table public.employee_tasks add column if not exists due_at timestamptz';
    execute 'alter table public.employee_tasks add column if not exists priority text default ''normal'' default ''normal''';
    execute 'alter table public.employee_tasks add column if not exists status text default ''todo''';
    execute 'alter table public.employee_tasks add column if not exists metadata jsonb default ''{}''::jsonb';
    execute 'alter table public.employee_tasks add column if not exists created_at timestamptz default now() default now()';
    execute 'alter table public.employee_tasks add column if not exists updated_at timestamptz default now() default now()';
end
$$;

do $$
begin
  if to_regclass('public.business_assets') is null then
    raise notice 'skipping business_assets: table not present';
    return;
  end if;

    execute 'alter table public.business_assets add column if not exists organization_id uuid';
    execute 'alter table public.business_assets add column if not exists location_id uuid';
    execute 'alter table public.business_assets add column if not exists name text';
    execute 'alter table public.business_assets add column if not exists asset_type text default ''equipment''';
    execute 'alter table public.business_assets add column if not exists serial_number text';
    execute 'alter table public.business_assets add column if not exists purchase_date date';
    execute 'alter table public.business_assets add column if not exists purchase_cost_cents integer';
    execute 'alter table public.business_assets add column if not exists status text default ''active''';
    execute 'alter table public.business_assets add column if not exists metadata jsonb default ''{}''::jsonb';
    execute 'alter table public.business_assets add column if not exists created_at timestamptz default now() default now()';
    execute 'alter table public.business_assets add column if not exists updated_at timestamptz default now() default now()';
end
$$;

do $$
begin
  if to_regclass('public.vehicle_records') is null then
    raise notice 'skipping vehicle_records: table not present';
    return;
  end if;

    execute 'alter table public.vehicle_records add column if not exists organization_id uuid';
    execute 'alter table public.vehicle_records add column if not exists asset_id uuid';
    execute 'alter table public.vehicle_records add column if not exists vehicle_type text default ''vehicle''';
    execute 'alter table public.vehicle_records add column if not exists make text';
    execute 'alter table public.vehicle_records add column if not exists model text';
    execute 'alter table public.vehicle_records add column if not exists year integer';
    execute 'alter table public.vehicle_records add column if not exists plate_number text';
    execute 'alter table public.vehicle_records add column if not exists vin text';
    execute 'alter table public.vehicle_records add column if not exists insurance_policy text';
    execute 'alter table public.vehicle_records add column if not exists registration_expires_at date';
    execute 'alter table public.vehicle_records add column if not exists status text default ''active''';
    execute 'alter table public.vehicle_records add column if not exists metadata jsonb default ''{}''::jsonb';
    execute 'alter table public.vehicle_records add column if not exists created_at timestamptz default now() default now()';
    execute 'alter table public.vehicle_records add column if not exists updated_at timestamptz default now() default now()';
end
$$;

do $$
begin
  if to_regclass('public.maintenance_logs') is null then
    raise notice 'skipping maintenance_logs: table not present';
    return;
  end if;

    execute 'alter table public.maintenance_logs add column if not exists organization_id uuid';
    execute 'alter table public.maintenance_logs add column if not exists asset_id uuid';
    execute 'alter table public.maintenance_logs add column if not exists vehicle_id uuid';
    execute 'alter table public.maintenance_logs add column if not exists service_type text';
    execute 'alter table public.maintenance_logs add column if not exists description text';
    execute 'alter table public.maintenance_logs add column if not exists vendor text';
    execute 'alter table public.maintenance_logs add column if not exists cost_cents integer default 0 default 0';
    execute 'alter table public.maintenance_logs add column if not exists currency text default ''usd'' default ''usd''';
    execute 'alter table public.maintenance_logs add column if not exists serviced_at date';
    execute 'alter table public.maintenance_logs add column if not exists next_due_at date';
    execute 'alter table public.maintenance_logs add column if not exists status text default ''completed''';
    execute 'alter table public.maintenance_logs add column if not exists created_at timestamptz default now() default now()';
    execute 'alter table public.maintenance_logs add column if not exists updated_at timestamptz default now() default now()';
end
$$;

do $$
begin
  if to_regclass('public.inventory_items') is null then
    raise notice 'skipping inventory_items: table not present';
    return;
  end if;

    execute 'alter table public.inventory_items add column if not exists organization_id uuid';
    execute 'alter table public.inventory_items add column if not exists location_id uuid';
    execute 'alter table public.inventory_items add column if not exists name text';
    execute 'alter table public.inventory_items add column if not exists sku text';
    execute 'alter table public.inventory_items add column if not exists category text';
    execute 'alter table public.inventory_items add column if not exists quantity numeric(12,2) default 0 default 0';
    execute 'alter table public.inventory_items add column if not exists unit text default ''each'' default ''each''';
    execute 'alter table public.inventory_items add column if not exists reorder_level numeric(12,2)';
    execute 'alter table public.inventory_items add column if not exists cost_cents integer';
    execute 'alter table public.inventory_items add column if not exists price_cents integer';
    execute 'alter table public.inventory_items add column if not exists status text default ''active''';
    execute 'alter table public.inventory_items add column if not exists metadata jsonb default ''{}''::jsonb';
    execute 'alter table public.inventory_items add column if not exists created_at timestamptz default now() default now()';
    execute 'alter table public.inventory_items add column if not exists updated_at timestamptz default now() default now()';
end
$$;

do $$
begin
  if to_regclass('public.music_projects') is null then
    raise notice 'skipping music_projects: table not present';
    return;
  end if;

    execute 'alter table public.music_projects add column if not exists organization_id uuid';
    execute 'alter table public.music_projects add column if not exists platform_id uuid';
    execute 'alter table public.music_projects add column if not exists user_id uuid';
    execute 'alter table public.music_projects add column if not exists title text';
    execute 'alter table public.music_projects add column if not exists artist_name text';
    execute 'alter table public.music_projects add column if not exists project_type text default ''song''';
    execute 'alter table public.music_projects add column if not exists bpm integer';
    execute 'alter table public.music_projects add column if not exists musical_key text';
    execute 'alter table public.music_projects add column if not exists status text default ''draft''';
    execute 'alter table public.music_projects add column if not exists metadata jsonb default ''{}''::jsonb';
    execute 'alter table public.music_projects add column if not exists created_at timestamptz default now() default now()';
    execute 'alter table public.music_projects add column if not exists updated_at timestamptz default now() default now()';
end
$$;

do $$
begin
  if to_regclass('public.daw_sessions') is null then
    raise notice 'skipping daw_sessions: table not present';
    return;
  end if;

    execute 'alter table public.daw_sessions add column if not exists organization_id uuid';
    execute 'alter table public.daw_sessions add column if not exists music_project_id uuid';
    execute 'alter table public.daw_sessions add column if not exists daw_name text';
    execute 'alter table public.daw_sessions add column if not exists session_name text';
    execute 'alter table public.daw_sessions add column if not exists tempo_bpm integer';
    execute 'alter table public.daw_sessions add column if not exists sample_rate integer';
    execute 'alter table public.daw_sessions add column if not exists bit_depth integer';
    execute 'alter table public.daw_sessions add column if not exists file_reference text';
    execute 'alter table public.daw_sessions add column if not exists status text default ''active''';
    execute 'alter table public.daw_sessions add column if not exists metadata jsonb default ''{}''::jsonb';
    execute 'alter table public.daw_sessions add column if not exists created_at timestamptz default now() default now()';
    execute 'alter table public.daw_sessions add column if not exists updated_at timestamptz default now() default now()';
end
$$;

do $$
begin
  if to_regclass('public.audio_assets') is null then
    raise notice 'skipping audio_assets: table not present';
    return;
  end if;

    execute 'alter table public.audio_assets add column if not exists organization_id uuid';
    execute 'alter table public.audio_assets add column if not exists music_project_id uuid';
    execute 'alter table public.audio_assets add column if not exists daw_session_id uuid';
    execute 'alter table public.audio_assets add column if not exists title text';
    execute 'alter table public.audio_assets add column if not exists asset_type text default ''audio''';
    execute 'alter table public.audio_assets add column if not exists storage_path text';
    execute 'alter table public.audio_assets add column if not exists external_url text';
    execute 'alter table public.audio_assets add column if not exists duration_seconds numeric(12,3)';
    execute 'alter table public.audio_assets add column if not exists bpm integer';
    execute 'alter table public.audio_assets add column if not exists musical_key text';
    execute 'alter table public.audio_assets add column if not exists metadata jsonb default ''{}''::jsonb';
    execute 'alter table public.audio_assets add column if not exists status text default ''draft''';
    execute 'alter table public.audio_assets add column if not exists created_at timestamptz default now() default now()';
    execute 'alter table public.audio_assets add column if not exists updated_at timestamptz default now() default now()';
end
$$;

do $$
begin
  if to_regclass('public.vendor_accounts') is null then
    raise notice 'skipping vendor_accounts: table not present';
    return;
  end if;

    execute 'alter table public.vendor_accounts add column if not exists organization_id uuid';
    execute 'alter table public.vendor_accounts add column if not exists location_id uuid';
    execute 'alter table public.vendor_accounts add column if not exists name text';
    execute 'alter table public.vendor_accounts add column if not exists account_number text';
    execute 'alter table public.vendor_accounts add column if not exists contact_name text';
    execute 'alter table public.vendor_accounts add column if not exists email text';
    execute 'alter table public.vendor_accounts add column if not exists phone text';
    execute 'alter table public.vendor_accounts add column if not exists website text';
    execute 'alter table public.vendor_accounts add column if not exists payment_terms text';
    execute 'alter table public.vendor_accounts add column if not exists status text default ''active''';
    execute 'alter table public.vendor_accounts add column if not exists metadata jsonb default ''{}''::jsonb';
    execute 'alter table public.vendor_accounts add column if not exists created_at timestamptz default now() default now()';
    execute 'alter table public.vendor_accounts add column if not exists updated_at timestamptz default now() default now()';
end
$$;

do $$
begin
  if to_regclass('public.vendor_invoices') is null then
    raise notice 'skipping vendor_invoices: table not present';
    return;
  end if;

    execute 'alter table public.vendor_invoices add column if not exists organization_id uuid';
    execute 'alter table public.vendor_invoices add column if not exists location_id uuid';
    execute 'alter table public.vendor_invoices add column if not exists vendor_id uuid';
    execute 'alter table public.vendor_invoices add column if not exists invoice_number text';
    execute 'alter table public.vendor_invoices add column if not exists invoice_date date';
    execute 'alter table public.vendor_invoices add column if not exists due_date date';
    execute 'alter table public.vendor_invoices add column if not exists subtotal_cents integer default 0 default 0';
    execute 'alter table public.vendor_invoices add column if not exists tax_cents integer default 0 default 0';
    execute 'alter table public.vendor_invoices add column if not exists total_cents integer default 0 default 0';
    execute 'alter table public.vendor_invoices add column if not exists currency text default ''usd'' default ''usd''';
    execute 'alter table public.vendor_invoices add column if not exists document_url text';
    execute 'alter table public.vendor_invoices add column if not exists processing_status text default ''draft''';
    execute 'alter table public.vendor_invoices add column if not exists payment_status text default ''unpaid''';
    execute 'alter table public.vendor_invoices add column if not exists metadata jsonb default ''{}''::jsonb';
    execute 'alter table public.vendor_invoices add column if not exists created_by uuid';
    execute 'alter table public.vendor_invoices add column if not exists approved_by uuid';
    execute 'alter table public.vendor_invoices add column if not exists approved_at timestamptz';
    execute 'alter table public.vendor_invoices add column if not exists created_at timestamptz default now() default now()';
    execute 'alter table public.vendor_invoices add column if not exists updated_at timestamptz default now() default now()';
end
$$;

do $$
begin
  if to_regclass('public.recipe_cards') is null then
    raise notice 'skipping recipe_cards: table not present';
    return;
  end if;

    execute 'alter table public.recipe_cards add column if not exists organization_id uuid';
    execute 'alter table public.recipe_cards add column if not exists platform_id uuid';
    execute 'alter table public.recipe_cards add column if not exists name text';
    execute 'alter table public.recipe_cards add column if not exists category text';
    execute 'alter table public.recipe_cards add column if not exists yield_quantity numeric(12,3)';
    execute 'alter table public.recipe_cards add column if not exists yield_unit text';
    execute 'alter table public.recipe_cards add column if not exists instructions text';
    execute 'alter table public.recipe_cards add column if not exists status text default ''active''';
    execute 'alter table public.recipe_cards add column if not exists metadata jsonb default ''{}''::jsonb';
    execute 'alter table public.recipe_cards add column if not exists created_at timestamptz default now() default now()';
    execute 'alter table public.recipe_cards add column if not exists updated_at timestamptz default now() default now()';
end
$$;

do $$
begin
  if to_regclass('public.menu_items') is null then
    raise notice 'skipping menu_items: table not present';
    return;
  end if;

    execute 'alter table public.menu_items add column if not exists organization_id uuid';
    execute 'alter table public.menu_items add column if not exists platform_id uuid';
    execute 'alter table public.menu_items add column if not exists recipe_id uuid';
    execute 'alter table public.menu_items add column if not exists name text';
    execute 'alter table public.menu_items add column if not exists category text';
    execute 'alter table public.menu_items add column if not exists selling_price_cents integer default 0 default 0';
    execute 'alter table public.menu_items add column if not exists currency text default ''usd'' default ''usd''';
    execute 'alter table public.menu_items add column if not exists theoretical_cost_cents integer default 0 default 0';
    execute 'alter table public.menu_items add column if not exists target_food_cost_percent numeric(7,4)';
    execute 'alter table public.menu_items add column if not exists status text default ''active''';
    execute 'alter table public.menu_items add column if not exists metadata jsonb default ''{}''::jsonb';
    execute 'alter table public.menu_items add column if not exists created_at timestamptz default now() default now()';
    execute 'alter table public.menu_items add column if not exists updated_at timestamptz default now() default now()';
end
$$;

do $$
begin
  if to_regclass('public.pos_sales_summaries') is null then
    raise notice 'skipping pos_sales_summaries: table not present';
    return;
  end if;

    execute 'alter table public.pos_sales_summaries add column if not exists organization_id uuid';
    execute 'alter table public.pos_sales_summaries add column if not exists location_id uuid';
    execute 'alter table public.pos_sales_summaries add column if not exists business_date date';
    execute 'alter table public.pos_sales_summaries add column if not exists gross_sales_cents integer default 0 default 0';
    execute 'alter table public.pos_sales_summaries add column if not exists net_sales_cents integer default 0 default 0';
    execute 'alter table public.pos_sales_summaries add column if not exists discounts_cents integer default 0 default 0';
    execute 'alter table public.pos_sales_summaries add column if not exists refunds_cents integer default 0 default 0';
    execute 'alter table public.pos_sales_summaries add column if not exists tax_cents integer default 0 default 0';
    execute 'alter table public.pos_sales_summaries add column if not exists tips_cents integer default 0 default 0';
    execute 'alter table public.pos_sales_summaries add column if not exists tickets_count integer default 0 default 0';
    execute 'alter table public.pos_sales_summaries add column if not exists source text default ''manual'' default ''manual''';
    execute 'alter table public.pos_sales_summaries add column if not exists metadata jsonb default ''{}''::jsonb';
    execute 'alter table public.pos_sales_summaries add column if not exists created_at timestamptz default now() default now()';
    execute 'alter table public.pos_sales_summaries add column if not exists updated_at timestamptz default now() default now()';
end
$$;

do $$
begin
  if to_regclass('public.waste_logs') is null then
    raise notice 'skipping waste_logs: table not present';
    return;
  end if;

    execute 'alter table public.waste_logs add column if not exists organization_id uuid';
    execute 'alter table public.waste_logs add column if not exists location_id uuid';
    execute 'alter table public.waste_logs add column if not exists inventory_item_id uuid';
    execute 'alter table public.waste_logs add column if not exists item_name text';
    execute 'alter table public.waste_logs add column if not exists quantity numeric(12,3) default 0 default 0';
    execute 'alter table public.waste_logs add column if not exists unit text';
    execute 'alter table public.waste_logs add column if not exists estimated_cost_cents integer default 0 default 0';
    execute 'alter table public.waste_logs add column if not exists reason text';
    execute 'alter table public.waste_logs add column if not exists logged_by uuid';
    execute 'alter table public.waste_logs add column if not exists logged_at timestamptz default now() default now()';
    execute 'alter table public.waste_logs add column if not exists created_at timestamptz default now() default now()';
end
$$;

do $$
begin
  if to_regclass('public.daily_profit_snapshots') is null then
    raise notice 'skipping daily_profit_snapshots: table not present';
    return;
  end if;

    execute 'alter table public.daily_profit_snapshots add column if not exists organization_id uuid';
    execute 'alter table public.daily_profit_snapshots add column if not exists location_id uuid';
    execute 'alter table public.daily_profit_snapshots add column if not exists business_date date';
    execute 'alter table public.daily_profit_snapshots add column if not exists net_sales_cents integer default 0 default 0';
    execute 'alter table public.daily_profit_snapshots add column if not exists food_cost_cents integer default 0 default 0';
    execute 'alter table public.daily_profit_snapshots add column if not exists labor_cost_cents integer default 0 default 0';
    execute 'alter table public.daily_profit_snapshots add column if not exists controllable_expense_cents integer default 0 default 0';
    execute 'alter table public.daily_profit_snapshots add column if not exists gross_profit_cents integer default 0 default 0';
    execute 'alter table public.daily_profit_snapshots add column if not exists prime_cost_cents integer default 0 default 0';
    execute 'alter table public.daily_profit_snapshots add column if not exists food_cost_percent numeric(7,4)';
    execute 'alter table public.daily_profit_snapshots add column if not exists labor_cost_percent numeric(7,4)';
    execute 'alter table public.daily_profit_snapshots add column if not exists notes text';
    execute 'alter table public.daily_profit_snapshots add column if not exists source text default ''calculated'' default ''calculated''';
    execute 'alter table public.daily_profit_snapshots add column if not exists created_at timestamptz default now() default now()';
    execute 'alter table public.daily_profit_snapshots add column if not exists updated_at timestamptz default now() default now()';
end
$$;

do $$
begin
  if to_regclass('public.accounting_exports') is null then
    raise notice 'skipping accounting_exports: table not present';
    return;
  end if;

    execute 'alter table public.accounting_exports add column if not exists organization_id uuid';
    execute 'alter table public.accounting_exports add column if not exists provider_key text';
    execute 'alter table public.accounting_exports add column if not exists export_type text default ''bills''';
    execute 'alter table public.accounting_exports add column if not exists status text default ''queued''';
    execute 'alter table public.accounting_exports add column if not exists period_start date';
    execute 'alter table public.accounting_exports add column if not exists period_end date';
    execute 'alter table public.accounting_exports add column if not exists file_url text';
    execute 'alter table public.accounting_exports add column if not exists payload jsonb default ''{}''::jsonb';
    execute 'alter table public.accounting_exports add column if not exists error_message text';
    execute 'alter table public.accounting_exports add column if not exists created_by uuid';
    execute 'alter table public.accounting_exports add column if not exists created_at timestamptz default now() default now()';
    execute 'alter table public.accounting_exports add column if not exists updated_at timestamptz default now() default now()';
end
$$;

do $$
begin
  if to_regclass('public.device_capability_profiles') is null then
    raise notice 'skipping device_capability_profiles: table not present';
    return;
  end if;

    execute 'alter table public.device_capability_profiles add column if not exists organization_id uuid';
    execute 'alter table public.device_capability_profiles add column if not exists user_id uuid';
    execute 'alter table public.device_capability_profiles add column if not exists device_label text';
    execute 'alter table public.device_capability_profiles add column if not exists user_agent_hash text';
    execute 'alter table public.device_capability_profiles add column if not exists platform text';
    execute 'alter table public.device_capability_profiles add column if not exists supports_audio boolean default false default false';
    execute 'alter table public.device_capability_profiles add column if not exists supports_vibration boolean default false default false';
    execute 'alter table public.device_capability_profiles add column if not exists supports_geolocation boolean default false default false';
    execute 'alter table public.device_capability_profiles add column if not exists supports_device_motion boolean default false default false';
    execute 'alter table public.device_capability_profiles add column if not exists supports_device_orientation boolean default false default false';
    execute 'alter table public.device_capability_profiles add column if not exists supports_haptics boolean default false default false';
    execute 'alter table public.device_capability_profiles add column if not exists permission_state jsonb default ''{}''::jsonb';
    execute 'alter table public.device_capability_profiles add column if not exists last_seen_at timestamptz default now() default now()';
    execute 'alter table public.device_capability_profiles add column if not exists metadata jsonb default ''{}''::jsonb';
    execute 'alter table public.device_capability_profiles add column if not exists created_at timestamptz default now() default now()';
    execute 'alter table public.device_capability_profiles add column if not exists updated_at timestamptz default now() default now()';
end
$$;

do $$
begin
  if to_regclass('public.sensory_feedback_profiles') is null then
    raise notice 'skipping sensory_feedback_profiles: table not present';
    return;
  end if;

    execute 'alter table public.sensory_feedback_profiles add column if not exists organization_id uuid';
    execute 'alter table public.sensory_feedback_profiles add column if not exists platform_id uuid';
    execute 'alter table public.sensory_feedback_profiles add column if not exists name text';
    execute 'alter table public.sensory_feedback_profiles add column if not exists profile_key text';
    execute 'alter table public.sensory_feedback_profiles add column if not exists description text';
    execute 'alter table public.sensory_feedback_profiles add column if not exists sound_enabled boolean default true default true';
    execute 'alter table public.sensory_feedback_profiles add column if not exists vibration_enabled boolean default true default true';
    execute 'alter table public.sensory_feedback_profiles add column if not exists motion_enabled boolean default false default false';
    execute 'alter table public.sensory_feedback_profiles add column if not exists location_enabled boolean default false default false';
    execute 'alter table public.sensory_feedback_profiles add column if not exists accessibility_mode text default ''standard''';
    execute 'alter table public.sensory_feedback_profiles add column if not exists config jsonb default ''{}''::jsonb';
    execute 'alter table public.sensory_feedback_profiles add column if not exists status text default ''active''';
    execute 'alter table public.sensory_feedback_profiles add column if not exists created_at timestamptz default now() default now()';
    execute 'alter table public.sensory_feedback_profiles add column if not exists updated_at timestamptz default now() default now()';
end
$$;

do $$
begin
  if to_regclass('public.sound_cues') is null then
    raise notice 'skipping sound_cues: table not present';
    return;
  end if;

    execute 'alter table public.sound_cues add column if not exists organization_id uuid';
    execute 'alter table public.sound_cues add column if not exists feedback_profile_id uuid';
    execute 'alter table public.sound_cues add column if not exists cue_key text';
    execute 'alter table public.sound_cues add column if not exists name text';
    execute 'alter table public.sound_cues add column if not exists event_name text';
    execute 'alter table public.sound_cues add column if not exists sound_type text default ''tone''';
    execute 'alter table public.sound_cues add column if not exists frequency_hz numeric(10,2)';
    execute 'alter table public.sound_cues add column if not exists duration_ms integer default 120 default 120';
    execute 'alter table public.sound_cues add column if not exists volume numeric(5,2) default 0.25 default 0.25';
    execute 'alter table public.sound_cues add column if not exists asset_url text';
    execute 'alter table public.sound_cues add column if not exists config jsonb default ''{}''::jsonb';
    execute 'alter table public.sound_cues add column if not exists status text default ''active''';
    execute 'alter table public.sound_cues add column if not exists created_at timestamptz default now() default now()';
    execute 'alter table public.sound_cues add column if not exists updated_at timestamptz default now() default now()';
end
$$;

do $$
begin
  if to_regclass('public.haptic_patterns') is null then
    raise notice 'skipping haptic_patterns: table not present';
    return;
  end if;

    execute 'alter table public.haptic_patterns add column if not exists organization_id uuid';
    execute 'alter table public.haptic_patterns add column if not exists feedback_profile_id uuid';
    execute 'alter table public.haptic_patterns add column if not exists pattern_key text';
    execute 'alter table public.haptic_patterns add column if not exists name text';
    execute 'alter table public.haptic_patterns add column if not exists event_name text';
    execute 'alter table public.haptic_patterns add column if not exists vibration_pattern_ms integer[] default array[40]';
    execute 'alter table public.haptic_patterns add column if not exists intensity numeric(5,2)';
    execute 'alter table public.haptic_patterns add column if not exists fallback_sound_cue_id uuid';
    execute 'alter table public.haptic_patterns add column if not exists accessibility_notes text';
    execute 'alter table public.haptic_patterns add column if not exists status text default ''active''';
    execute 'alter table public.haptic_patterns add column if not exists created_at timestamptz default now() default now()';
    execute 'alter table public.haptic_patterns add column if not exists updated_at timestamptz default now() default now()';
end
$$;

do $$
begin
  if to_regclass('public.tactile_events') is null then
    raise notice 'skipping tactile_events: table not present';
    return;
  end if;

    execute 'alter table public.tactile_events add column if not exists organization_id uuid';
    execute 'alter table public.tactile_events add column if not exists platform_id uuid';
    execute 'alter table public.tactile_events add column if not exists user_id uuid';
    execute 'alter table public.tactile_events add column if not exists event_name text';
    execute 'alter table public.tactile_events add column if not exists event_context text';
    execute 'alter table public.tactile_events add column if not exists haptic_pattern_id uuid';
    execute 'alter table public.tactile_events add column if not exists sound_cue_id uuid';
    execute 'alter table public.tactile_events add column if not exists device_capability_profile_id uuid';
    execute 'alter table public.tactile_events add column if not exists status text default ''queued''';
    execute 'alter table public.tactile_events add column if not exists result_data jsonb default ''{}''::jsonb';
    execute 'alter table public.tactile_events add column if not exists created_at timestamptz default now() default now()';
end
$$;

do $$
begin
  if to_regclass('public.motion_sensor_events') is null then
    raise notice 'skipping motion_sensor_events: table not present';
    return;
  end if;

    execute 'alter table public.motion_sensor_events add column if not exists organization_id uuid';
    execute 'alter table public.motion_sensor_events add column if not exists platform_id uuid';
    execute 'alter table public.motion_sensor_events add column if not exists user_id uuid';
    execute 'alter table public.motion_sensor_events add column if not exists device_capability_profile_id uuid';
    execute 'alter table public.motion_sensor_events add column if not exists source text default ''browser''';
    execute 'alter table public.motion_sensor_events add column if not exists event_type text';
    execute 'alter table public.motion_sensor_events add column if not exists alpha numeric(12,6)';
    execute 'alter table public.motion_sensor_events add column if not exists beta numeric(12,6)';
    execute 'alter table public.motion_sensor_events add column if not exists gamma numeric(12,6)';
    execute 'alter table public.motion_sensor_events add column if not exists acceleration_x numeric(12,6)';
    execute 'alter table public.motion_sensor_events add column if not exists acceleration_y numeric(12,6)';
    execute 'alter table public.motion_sensor_events add column if not exists acceleration_z numeric(12,6)';
    execute 'alter table public.motion_sensor_events add column if not exists rotation_alpha numeric(12,6)';
    execute 'alter table public.motion_sensor_events add column if not exists rotation_beta numeric(12,6)';
    execute 'alter table public.motion_sensor_events add column if not exists rotation_gamma numeric(12,6)';
    execute 'alter table public.motion_sensor_events add column if not exists gesture_label text';
    execute 'alter table public.motion_sensor_events add column if not exists captured_at timestamptz default now() default now()';
    execute 'alter table public.motion_sensor_events add column if not exists metadata jsonb default ''{}''::jsonb';
    execute 'alter table public.motion_sensor_events add column if not exists created_at timestamptz default now() default now()';
end
$$;

do $$
begin
  if to_regclass('public.location_zones') is null then
    raise notice 'skipping location_zones: table not present';
    return;
  end if;

    execute 'alter table public.location_zones add column if not exists organization_id uuid';
    execute 'alter table public.location_zones add column if not exists location_id uuid';
    execute 'alter table public.location_zones add column if not exists name text';
    execute 'alter table public.location_zones add column if not exists zone_type text default ''business''';
    execute 'alter table public.location_zones add column if not exists latitude numeric(10,7)';
    execute 'alter table public.location_zones add column if not exists longitude numeric(10,7)';
    execute 'alter table public.location_zones add column if not exists radius_meters integer default 100 default 100';
    execute 'alter table public.location_zones add column if not exists polygon_geojson jsonb';
    execute 'alter table public.location_zones add column if not exists status text default ''active''';
    execute 'alter table public.location_zones add column if not exists metadata jsonb default ''{}''::jsonb';
    execute 'alter table public.location_zones add column if not exists created_at timestamptz default now() default now()';
    execute 'alter table public.location_zones add column if not exists updated_at timestamptz default now() default now()';
end
$$;

do $$
begin
  if to_regclass('public.location_events') is null then
    raise notice 'skipping location_events: table not present';
    return;
  end if;

    execute 'alter table public.location_events add column if not exists organization_id uuid';
    execute 'alter table public.location_events add column if not exists platform_id uuid';
    execute 'alter table public.location_events add column if not exists user_id uuid';
    execute 'alter table public.location_events add column if not exists employee_id uuid';
    execute 'alter table public.location_events add column if not exists location_zone_id uuid';
    execute 'alter table public.location_events add column if not exists event_type text';
    execute 'alter table public.location_events add column if not exists latitude numeric(10,7)';
    execute 'alter table public.location_events add column if not exists longitude numeric(10,7)';
    execute 'alter table public.location_events add column if not exists accuracy_meters numeric(10,2)';
    execute 'alter table public.location_events add column if not exists altitude_meters numeric(10,2)';
    execute 'alter table public.location_events add column if not exists speed_mps numeric(10,3)';
    execute 'alter table public.location_events add column if not exists heading_degrees numeric(10,3)';
    execute 'alter table public.location_events add column if not exists captured_at timestamptz default now() default now()';
    execute 'alter table public.location_events add column if not exists privacy_mode text default ''precise''';
    execute 'alter table public.location_events add column if not exists metadata jsonb default ''{}''::jsonb';
    execute 'alter table public.location_events add column if not exists created_at timestamptz default now() default now()';
end
$$;

do $$
begin
  if to_regclass('public.creator_artist_profiles') is null then
    raise notice 'skipping creator_artist_profiles: table not present';
    return;
  end if;

    execute 'alter table public.creator_artist_profiles add column if not exists organization_id uuid';
    execute 'alter table public.creator_artist_profiles add column if not exists platform_id uuid';
    execute 'alter table public.creator_artist_profiles add column if not exists user_id uuid';
    execute 'alter table public.creator_artist_profiles add column if not exists artist_name text';
    execute 'alter table public.creator_artist_profiles add column if not exists artist_key text';
    execute 'alter table public.creator_artist_profiles add column if not exists public_description text';
    execute 'alter table public.creator_artist_profiles add column if not exists private_backstory jsonb default ''{}''::jsonb';
    execute 'alter table public.creator_artist_profiles add column if not exists voice_identity jsonb default ''{}''::jsonb';
    execute 'alter table public.creator_artist_profiles add column if not exists genre_blend jsonb default ''{}''::jsonb';
    execute 'alter table public.creator_artist_profiles add column if not exists writing_rules jsonb default ''{}''::jsonb';
    execute 'alter table public.creator_artist_profiles add column if not exists visual_rules jsonb default ''{}''::jsonb';
    execute 'alter table public.creator_artist_profiles add column if not exists prompt_rules jsonb default ''{}''::jsonb';
    execute 'alter table public.creator_artist_profiles add column if not exists status text default ''active''';
    execute 'alter table public.creator_artist_profiles add column if not exists created_at timestamptz default now() default now()';
    execute 'alter table public.creator_artist_profiles add column if not exists updated_at timestamptz default now() default now()';
end
$$;

do $$
begin
  if to_regclass('public.customers') is null then
    raise notice 'skipping customers: table not present';
    return;
  end if;

    execute 'alter table public.customers add column if not exists organization_id uuid';
    execute 'alter table public.customers add column if not exists name text';
    execute 'alter table public.customers add column if not exists email text';
    execute 'alter table public.customers add column if not exists phone text';
    execute 'alter table public.customers add column if not exists status text default ''active''';
    execute 'alter table public.customers add column if not exists source text';
    execute 'alter table public.customers add column if not exists tags text[] default ''{}''';
    execute 'alter table public.customers add column if not exists communication_preference text default ''unknown''';
    execute 'alter table public.customers add column if not exists created_by uuid';
    execute 'alter table public.customers add column if not exists created_at timestamptz default now()';
    execute 'alter table public.customers add column if not exists updated_at timestamptz default now()';
    execute 'alter table public.customers add column if not exists metadata jsonb default ''{}''::jsonb';
end
$$;

do $$
begin
  if to_regclass('public.quotes') is null then
    raise notice 'skipping quotes: table not present';
    return;
  end if;

    execute 'alter table public.quotes add column if not exists organization_id uuid';
    execute 'alter table public.quotes add column if not exists customer_id uuid';
    execute 'alter table public.quotes add column if not exists title text';
    execute 'alter table public.quotes add column if not exists amount_cents integer';
    execute 'alter table public.quotes add column if not exists status text default ''draft''';
    execute 'alter table public.quotes add column if not exists created_by uuid';
    execute 'alter table public.quotes add column if not exists created_at timestamptz default now()';
    execute 'alter table public.quotes add column if not exists updated_at timestamptz default now()';
    execute 'alter table public.quotes add column if not exists metadata jsonb default ''{}''::jsonb';
end
$$;
