-- Introducing two browsers to each other, so they can call without us.
--
-- A WebRTC call is direct. The audio goes peer to peer and never touches this
-- application, which is what makes a call cost nothing however long it lasts.
-- What two browsers cannot do on their own is find each other: one has to hand
-- the other a session description and a list of network candidates. These two
-- tables are that exchange and nothing else.
--
-- ## Why the signalling is rows in a table rather than a socket
--
-- The obvious way to signal is a WebSocket. This application is an Express app
-- running as a Vercel serverless function -- there is no long-lived process to
-- hold a socket open, and pretending otherwise would produce a call that works
-- locally and never in production.
--
-- So each side writes its offer, answer and candidates as rows and reads the
-- other side's back. It costs a few small requests during setup, and **nothing
-- at all once the call connects**, because from that moment the two browsers
-- are talking to each other and this application is not involved.
--
-- ## What a join token is, and what it is not
--
-- `join_token` is a bearer capability: whoever holds the link can join that one
-- call. It is not an account, it does not identify the person, and it grants
-- nothing beyond the single conversation it names. That is deliberate -- the
-- other side of a call from a customer record is a customer, and requiring them
-- to hold an account before they can answer the phone would be a product nobody
-- uses.
--
-- Three properties make a bearer token defensible here, and all three are
-- enforced rather than intended:
--
--   It is unguessable. 32 random bytes, generated by node:crypto.
--   It expires. `expires_at` is not null and is checked on every read.
--   It can be killed. Ending a call is a status change, and an ended call
--   answers nothing.
--
-- ## What is deliberately not here
--
-- **No recording, no transcript, no duration billing, and no audio column of
-- any kind.** The media never reaches this application, and a schema that left
-- room for it would be an invitation to route it through here later. Recording
-- a call is also a consent decision in most of the places this product is used,
-- and AGENTS.md puts unknown sensitive actions behind owner review rather than
-- behind a column default.
--
-- **No customer name, email or phone.** `customer_id` points at the record the
-- call was placed from. Copying the person's details onto the call row would
-- put contact details behind a bearer token.

create table if not exists public.call_sessions (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations(id) on delete cascade,

  -- The record the call was placed from. Nullable because a call may outlive
  -- the customer record it started from, and losing the call history when
  -- somebody tidies up their contacts would be worse than a null here.
  customer_id uuid references public.customers(id) on delete set null,

  -- Who placed it. Not used for access -- the call belongs to the organization,
  -- like every other row here.
  created_by uuid,

  -- The bearer capability. See the header: unguessable, expiring, revocable.
  join_token text not null,

  status text not null default 'ringing'
    check (status in ('ringing', 'connected', 'ended', 'missed')),

  -- When the two sides actually connected, as reported by the browsers. Null
  -- until then, and null for ever on a call nobody answered -- which is exactly
  -- what distinguishes 'missed' from 'ended' without a second column agreeing
  -- with the first.
  connected_at timestamptz,
  ended_at timestamptz,

  -- Free text from whichever side hung up, for a page that has to say what
  -- happened. Never parsed and never used for a decision.
  end_reason text,

  created_at timestamptz not null default now(),

  -- Not null on purpose. A signalling row with no expiry is a permanent way in,
  -- and "we will set it in the application" is how one ends up null.
  expires_at timestamptz not null
);

-- One live call per token. A collision would let a second call read the first
-- one's signals, which is the one thing this table must make impossible.
create unique index if not exists call_sessions_join_token_unique
  on public.call_sessions (join_token);

create index if not exists call_sessions_organization_created_idx
  on public.call_sessions (organization_id, created_at desc);

create index if not exists call_sessions_customer_idx
  on public.call_sessions (customer_id, created_at desc);

alter table public.call_sessions
  drop constraint if exists call_sessions_join_token_length;

-- 32 random bytes as base64url is 43 characters. Checked here as well as
-- generated in code, because a short token is not a bug that shows up in
-- testing -- it is a bug that shows up as somebody else on the call.
alter table public.call_sessions
  add constraint call_sessions_join_token_length
  check (join_token ~ '^[A-Za-z0-9_-]{40,64}$');

alter table public.call_sessions
  drop constraint if exists call_sessions_ended_has_time;

-- An ended call has an ending. Without this, 'ended' with a null ended_at
-- renders as a call that finished at no particular time, which every page
-- displaying it then has to invent a sentence for.
alter table public.call_sessions
  add constraint call_sessions_ended_has_time
  check (status <> 'ended' or ended_at is not null);

-- ---------------------------------------------------------------------------

create table if not exists public.call_signals (
  id uuid primary key default gen_random_uuid(),
  call_id uuid not null references public.call_sessions(id) on delete cascade,

  -- Carried on the signal as well as on the session. The session is the tenant
  -- boundary, and a join to reach it on every poll is a join every reader has
  -- to remember to write. This column is what lets the filter be the same one
  -- as everywhere else in this codebase.
  organization_id uuid not null references public.organizations(id) on delete cascade,

  -- Which end sent it. Each side polls for what the other side sent, so this is
  -- what stops a browser being handed its own offer back and negotiating with
  -- itself.
  from_role text not null check (from_role in ('business', 'customer')),

  kind text not null check (kind in ('offer', 'answer', 'candidate', 'bye')),

  -- The session description or ICE candidate, exactly as the browser produced
  -- it. Never parsed here and never rendered as anything but JSON: an SDP is
  -- attacker-influenced text as far as this application is concerned, and the
  -- only safe thing to do with it is hand it to the other RTCPeerConnection.
  payload jsonb not null,

  created_at timestamptz not null default now()
);

-- The poll: everything on this call from the other side, in order, after a
-- cursor. The index matches that query exactly.
create index if not exists call_signals_call_created_idx
  on public.call_signals (call_id, created_at);

-- ---------------------------------------------------------------------------
-- Row level security.
-- ---------------------------------------------------------------------------
--
-- Enabled with no policies, matching push_subscriptions, business_payment_accounts
-- and scroll_sites. Every route reading these tables goes through the service
-- role and carries its own organization_id filter, and the customer side
-- carries a join token checked against a single row.
--
-- There must never be a public read of call_signals. A list of them across
-- tenants is every network address of every device that has ever been on a
-- call here.
alter table public.call_sessions enable row level security;
alter table public.call_signals enable row level security;

comment on table public.call_sessions is
  'One browser-to-browser call. The audio is peer to peer and never reaches this application; this row exists so the two sides can find each other. join_token is a bearer capability: unguessable, expiring, and revoked by ending the call.';

comment on table public.call_signals is
  'WebRTC offers, answers and ICE candidates in transit between the two ends of one call. Written by one side, polled by the other, and never interpreted here.';
