-- Sixteen formulas the runtime evaluates could never be saved.
--
-- sonara_formula_results.formula_key references sonara_formula_definitions, and
-- these keys were added to lib/sonara-formula-library.cjs without a row here, so
-- every save of one was refused by the foreign key -- and the route reported
-- that refusal as "setup_required", which told the owner to finish a setup that
-- was already finished. 20261004130000 seeded twelve the same way; these were
-- missed then. tests/every-formula-can-be-saved.test.js now fails when a formula
-- is added to the library without a row in a migration.
--
-- No new tables, grants or customer records. Existing definitions are preserved.
INSERT INTO public.sonara_formula_definitions
  (formula_key,group_key,product_area,label,public_label,expression_text,required_inputs,target_tables,output_unit,role_visibility,status,notes)
VALUES
  ('ltv_to_cac_ratio','growth_marketing','Growth Studio','LTV to CAC ratio','LTV to CAC ratio','customer_lifetime_value / customer_acquisition_cost','["customer_lifetime_value","customer_acquisition_cost"]','["growth_campaigns","customer_records"]','ratio','["owner","admin"]','active','Evaluated by lib/sonara-formula-library.cjs; seeded so a saved result satisfies its formula-key foreign key.'),
  ('waste_cost','restaurant_margin','Business Builder','Waste cost','Waste cost','waste_quantity * unit_cost','["waste_quantity","unit_cost"]','["waste_logs","inventory_items"]','money','["owner","admin"]','active','Evaluated by lib/sonara-formula-library.cjs; seeded so a saved result satisfies its formula-key foreign key.'),
  ('break_even_sales','restaurant_margin','Business Builder','Break-even sales','Break-even sales','fixed_costs / gross_margin_percent_decimal','["fixed_costs","gross_margin_percent_decimal"]','["daily_profit_snapshots"]','money','["owner","admin"]','active','Evaluated by lib/sonara-formula-library.cjs; seeded so a saved result satisfies its formula-key foreign key.'),
  ('wage_projection','employee_payroll','Business Builder','Wage projection','Wage projection','scheduled_hours * hourly_rate','["scheduled_hours","hourly_rate"]','["employee_shifts","employee_wage_rates"]','money','["owner","admin"]','active','Evaluated by lib/sonara-formula-library.cjs; seeded so a saved result satisfies its formula-key foreign key.'),
  ('employee_productivity','employee_payroll','Business Builder','Employee productivity','Employee productivity','sales / labor_hours','["sales","labor_hours"]','["employee_time_entries","pos_sales_summaries"]','money_per_hour','["owner","admin"]','active','Evaluated by lib/sonara-formula-library.cjs; seeded so a saved result satisfies its formula-key foreign key.'),
  ('stockout_risk_score','inventory_operations','Business Builder','Stockout risk','Stockout risk','max(0, reorder_point - current_stock)','["reorder_point","current_stock"]','["inventory_items"]','score','["owner","admin"]','active','Evaluated by lib/sonara-formula-library.cjs; seeded so a saved result satisfies its formula-key foreign key.'),
  ('vendor_total_cost','inventory_operations','Business Builder','Vendor total cost','Vendor total cost','item_cost + shipping + fees - discounts','["item_cost","shipping","fees","discounts"]','["vendor_invoices"]','money','["owner","admin"]','active','Evaluated by lib/sonara-formula-library.cjs; seeded so a saved result satisfies its formula-key foreign key.'),
  ('delivery_profit','inventory_operations','Business Builder','Delivery profit','Delivery profit','delivery_revenue - route_cost - packaging_cost','["delivery_revenue","route_cost","packaging_cost"]','["route_tracking_sessions","pos_sales_summaries"]','money','["owner","admin"]','active','Evaluated by lib/sonara-formula-library.cjs; seeded so a saved result satisfies its formula-key foreign key.'),
  ('follow_up_priority','growth_marketing','Growth Studio','Follow-up priority','Follow-up priority','lead_score + days_since_contact_weight + value_weight','["lead_score","days_since_contact_weight","value_weight"]','["growth_leads"]','score','["owner","admin"]','active','Evaluated by lib/sonara-formula-library.cjs; seeded so a saved result satisfies its formula-key foreign key.'),
  ('email_reply_rate','growth_marketing','Growth Studio','Email reply rate','Email reply rate','(replies / delivered_messages) * 100','["replies","delivered_messages"]','["growth_campaigns"]','percent','["owner","admin"]','active','Evaluated by lib/sonara-formula-library.cjs; seeded so a saved result satisfies its formula-key foreign key.'),
  ('booking_conversion','growth_marketing','Growth Studio','Booking conversion','Booking conversion','(bookings / booking_page_visits) * 100','["bookings","booking_page_visits"]','["business_appointments","growth_campaigns"]','percent','["owner","admin"]','active','Evaluated by lib/sonara-formula-library.cjs; seeded so a saved result satisfies its formula-key foreign key.'),
  ('originality_guard_score','creator_music','Creator Studio','Originality guard','Originality guard','100 - similarity_risk_score','["similarity_risk_score"]','["creator_quality_checks"]','score','["owner","admin"]','active','Evaluated by lib/sonara-formula-library.cjs; seeded so a saved result satisfies its formula-key foreign key.'),
  ('transcript_confidence_average','creator_music','Creator Studio','Transcript confidence','Transcript confidence','avg(segment_confidence)','["segment_confidence"]','["audio_transcription_segments"]','percent','["owner","admin"]','active','Evaluated by lib/sonara-formula-library.cjs; seeded so a saved result satisfies its formula-key foreign key.'),
  ('motion_safety_score','ui_device_experience','SONARA UI','Motion safety','Motion safety','reduced_motion_enabled ? 100 : animation_intensity_score','["reduced_motion_enabled","animation_intensity_score"]','["app_experience_settings"]','score','["owner","admin"]','active','Evaluated by lib/sonara-formula-library.cjs; seeded so a saved result satisfies its formula-key foreign key.'),
  ('workflow_priority_score','operating_twin','SONARA Admin','Workflow priority','Workflow priority','business_value + customer_value + deadline_weight - complexity','["business_value","customer_value","deadline_weight","complexity"]','["module_outputs"]','score','["owner","admin"]','active','Evaluated by lib/sonara-formula-library.cjs; seeded so a saved result satisfies its formula-key foreign key.'),
  ('risk_adjusted_value','operating_twin','SONARA Admin','Risk-adjusted value','Risk-adjusted value','expected_value * confidence_percent - risk_cost','["expected_value","confidence_percent","risk_cost"]','["module_outputs"]','money_or_score','["owner","admin"]','active','Evaluated by lib/sonara-formula-library.cjs; seeded so a saved result satisfies its formula-key foreign key.')
ON CONFLICT (formula_key) DO NOTHING;
