-- Copyright (c) 2026 SONARA Industries. All rights reserved.
-- Schema migration required for FK-safe saving of the new formula results.
-- No customer data, grants, policy changes or auto-generated business records.
-- Formula groups must exist before definitions due to group_key FK.
INSERT INTO public.sonara_formula_groups (group_key,label,product_area,description,status)
VALUES
  ('labor_economics','Labor and opportunity costs','Business Builder','Deterministic engineering estimates; not engineering approval.','active'),
  ('building_economics','Construction investment economics','Business Builder','Deterministic engineering estimates; not engineering approval.','active'),
  ('construction_trades','Construction and trade estimates','Business Builder','Deterministic engineering estimates; not engineering approval.','active'),
  ('trade_electrical','Electrical estimates','Business Builder','Deterministic engineering estimates; not engineering approval.','active'),
  ('trade_plumbing','Plumbing and pipe flow','Business Builder','Deterministic engineering estimates; not engineering approval.','active'),
  ('measurement_science','Measurement and unit conversion','Business Builder','Deterministic engineering estimates; not engineering approval.','active'),
  ('computing_engineering','Computing and processing costs','Creator Studio','Deterministic engineering estimates; not engineering approval.','active'),
  ('space_science','Space and optical science','Creator Studio','Deterministic engineering estimates; not engineering approval.','active'),
  ('quantum_research','Quantum measurement learning','Creator Studio','Deterministic engineering estimates; not engineering approval.','active')
ON CONFLICT (group_key) DO NOTHING;

INSERT INTO public.sonara_formula_definitions
  (formula_key,group_key,product_area,label,public_label,expression_text,required_inputs,target_tables,output_unit,role_visibility,status,notes)
VALUES
  ('fully_burdened_labor_cost','labor_economics','Business Builder','Fully burdened labor cost','Fully burdened labor cost','paid_hours * (hourly_wage + benefits_per_hour + payroll_taxes_per_hour + overhead_per_hour)','["paid_hours","hourly_wage","benefits_per_hour","payroll_taxes_per_hour","overhead_per_hour"]','[]','money','["owner","admin"]','active','Deterministic estimator; sources and limitations: docs/research/engineering-calculators-2026-10-09.md.'),
  ('trade_bid_price','construction_trades','Business Builder','Trade job bid estimate','Trade job bid estimate','((productive_hours / utilization_rate) * burdened_cost_per_paid_hour + materials_cost + other_direct_cost) * (1 + markup_rate)','["productive_hours","utilization_rate","burdened_cost_per_paid_hour","materials_cost","other_direct_cost","markup_rate"]','[]','money','["owner","admin"]','active','Deterministic estimator; sources and limitations: docs/research/engineering-calculators-2026-10-09.md.'),
  ('economic_profit','labor_economics','Business Builder','Economic profit after opportunity cost','Economic profit after opportunity cost','chosen_net_benefit - best_foregone_net_benefit','["chosen_net_benefit","best_foregone_net_benefit"]','[]','money','["owner","admin"]','active','Deterministic estimator; sources and limitations: docs/research/engineering-calculators-2026-10-09.md.'),
  ('project_net_present_value','building_economics','Business Builder','Project net present value','Project net present value','annual_net_cash_flow * (1 - (1 + discount_rate)^(-years)) / discount_rate - upfront_cost','["upfront_cost","annual_net_cash_flow","discount_rate","years"]','[]','money','["owner","admin"]','active','Deterministic estimator; sources and limitations: docs/research/engineering-calculators-2026-10-09.md.'),
  ('material_quantity_with_waste','construction_trades','Business Builder','Materials including waste','Materials including waste','net_quantity * (1 + waste_rate)','["net_quantity","waste_rate"]','[]','quantity','["owner","admin"]','active','Deterministic estimator; sources and limitations: docs/research/engineering-calculators-2026-10-09.md.'),
  ('concrete_volume_m3','construction_trades','Business Builder','Concrete geometric volume','Concrete geometric volume','length_meters * width_meters * depth_meters','["length_meters","width_meters","depth_meters"]','[]','cubic_meters','["owner","admin"]','active','Deterministic estimator; sources and limitations: docs/research/engineering-calculators-2026-10-09.md.'),
  ('roofing_squares','construction_trades','Business Builder','Roofing squares including waste','Roofing squares including waste','roof_area_square_feet * (1 + waste_rate) / 100','["roof_area_square_feet","waste_rate"]','[]','roofing_squares','["owner","admin"]','active','Deterministic estimator; sources and limitations: docs/research/engineering-calculators-2026-10-09.md.'),
  ('paint_gallons','construction_trades','Business Builder','Paint quantity in US gallons','Paint quantity in US gallons','surface_square_feet * coats * (1 + waste_rate) / coverage_square_feet_per_gallon','["surface_square_feet","coats","waste_rate","coverage_square_feet_per_gallon"]','[]','US_gallons','["owner","admin"]','active','Deterministic estimator; sources and limitations: docs/research/engineering-calculators-2026-10-09.md.'),
  ('single_phase_ac_real_power_watts','trade_electrical','Business Builder','Single-phase AC real power','Single-phase AC real power','rms_volts * rms_amps * power_factor','["rms_volts","rms_amps","power_factor"]','[]','watts','["owner","admin"]','active','Deterministic estimator; sources and limitations: docs/research/engineering-calculators-2026-10-09.md.'),
  ('pipe_flow_m3_s','trade_plumbing','Business Builder','Estimated circular pipe flow','Estimated circular pipe flow','pi * (inside_diameter_meters / 2)^2 * fluid_speed_meters_per_second','["inside_diameter_meters","fluid_speed_meters_per_second"]','[]','cubic_meters_per_second','["owner","admin"]','active','Deterministic estimator; sources and limitations: docs/research/engineering-calculators-2026-10-09.md.'),
  ('square_feet_to_square_meters','measurement_science','Business Builder','Square feet to square meters','Square feet to square meters','area_square_feet * 0.09290304','["area_square_feet"]','[]','square_meters','["owner","admin"]','active','Deterministic estimator; sources and limitations: docs/research/engineering-calculators-2026-10-09.md.'),
  ('byte_transfer_seconds','computing_engineering','Creator Studio','Theoretical transfer duration','Theoretical transfer duration','payload_bytes * 8 / effective_bits_per_second','["payload_bytes","effective_bits_per_second"]','[]','seconds','["owner","admin"]','active','Deterministic estimator; sources and limitations: docs/research/engineering-calculators-2026-10-09.md.'),
  ('compute_job_cost','computing_engineering','Creator Studio','Compute and storage job cost','Compute and storage job cost','runtime_seconds * compute_rate_per_hour / 3600 + storage_gib * storage_rate_per_gib_month * months_stored','["runtime_seconds","compute_rate_per_hour","storage_gib","storage_rate_per_gib_month","months_stored"]','[]','money','["owner","admin"]','active','Deterministic estimator; sources and limitations: docs/research/engineering-calculators-2026-10-09.md.'),
  ('satellite_orbital_period_seconds','space_science','Business Builder','Keplerian satellite orbital period','Keplerian satellite orbital period','2 * pi * sqrt(semi_major_axis_meters^3 / gravitational_parameter_m3_s2)','["semi_major_axis_meters","gravitational_parameter_m3_s2"]','[]','seconds','["owner","admin"]','active','Deterministic estimator; sources and limitations: docs/research/engineering-calculators-2026-10-09.md.'),
  ('telescope_rayleigh_arcseconds','space_science','Creator Studio','Diffraction-limited telescope resolution','Diffraction-limited telescope resolution','1.22 * wavelength_nanometers * 1e-9 / aperture_meters * 206264.806247','["wavelength_nanometers","aperture_meters"]','[]','arcseconds','["owner","admin"]','active','Deterministic estimator; sources and limitations: docs/research/engineering-calculators-2026-10-09.md.'),
  ('quantum_ideal_one_probability','quantum_research','Creator Studio','Ideal qubit one-state probability','Ideal qubit one-state probability','sin(rotation_radians / 2)^2','["rotation_radians"]','[]','probability','["owner","admin"]','active','Deterministic estimator; sources and limitations: docs/research/engineering-calculators-2026-10-09.md.'),
  ('quantum_sampling_standard_error','quantum_research','Creator Studio','Quantum measurement standard error','Quantum measurement standard error','sqrt(probability_one * (1 - probability_one) / shots)','["probability_one","shots"]','[]','probability','["owner","admin"]','active','Deterministic estimator; sources and limitations: docs/research/engineering-calculators-2026-10-09.md.')
ON CONFLICT (formula_key) DO NOTHING;
