-- Member-scoped SELECT policies for the tables the application reads.
--
-- GENERATED by scripts/generate-member-read-policies.cjs -- regenerate rather
-- than edit by hand.
--
-- Prerequisite for CRIT-3 item (2), user-scoped reads. Before this migration,
-- 184 of 206 tenant-scoped tables had no policy a signed-in user could read
-- through, so forwarding a caller's JWT would have returned zero rows and
-- blanked the workspace screens.
--
-- This migration is additive and cannot change existing behaviour:
--
--   * service_role bypasses RLS entirely, and every current query uses it
--   * nothing currently connects as `authenticated`
--   * no existing policy is dropped or altered; the policies created here have
--     their own names and only grant SELECT
--
-- Applying it makes user-scoped reads possible. It does not switch any read
-- over -- that is a separate, verifiable step once this has landed.

do $$
begin
  if to_regclass('public.organization_memberships') is null then
    raise exception 'organization_memberships is missing; member policies cannot be created';
  end if;
  if not exists (
    select 1 from pg_proc p
    join pg_namespace n on n.oid = p.pronamespace
    where n.nspname = 'public' and p.proname = 'is_org_member'
  ) then
    raise exception 'public.is_org_member() is missing; member policies would deny every row';
  end if;
end
$$;

-- Organization-scoped: any member of the owning organization may read.

do $$
begin
  if to_regclass('public.billing_entitlements') is null then
    raise notice 'skipping billing_entitlements: table not present';
    return;
  end if;
  if not exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'billing_entitlements'
      and column_name = 'organization_id'
  ) then
    raise notice 'skipping billing_entitlements: required organization_id column not present';
    return;
  end if;

  execute 'alter table public.billing_entitlements enable row level security';
  execute 'drop policy if exists "billing_entitlements_select_member" on public.billing_entitlements';
  execute 'create policy "billing_entitlements_select_member" on public.billing_entitlements for select to authenticated using (public.is_org_member(organization_id))';
end
$$;

do $$
begin
  if to_regclass('public.billing_subscriptions') is null then
    raise notice 'skipping billing_subscriptions: table not present';
    return;
  end if;
  if not exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'billing_subscriptions'
      and column_name = 'organization_id'
  ) then
    raise notice 'skipping billing_subscriptions: required organization_id column not present';
    return;
  end if;

  execute 'alter table public.billing_subscriptions enable row level security';
  execute 'drop policy if exists "billing_subscriptions_select_member" on public.billing_subscriptions';
  execute 'create policy "billing_subscriptions_select_member" on public.billing_subscriptions for select to authenticated using (public.is_org_member(organization_id))';
end
$$;

do $$
begin
  if to_regclass('public.business_memberships') is null then
    raise notice 'skipping business_memberships: table not present';
    return;
  end if;
  if not exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'business_memberships'
      and column_name = 'organization_id'
  ) then
    raise notice 'skipping business_memberships: required organization_id column not present';
    return;
  end if;

  execute 'alter table public.business_memberships enable row level security';
  execute 'drop policy if exists "business_memberships_select_member" on public.business_memberships';
  execute 'create policy "business_memberships_select_member" on public.business_memberships for select to authenticated using (public.is_org_member(organization_id))';
end
$$;

do $$
begin
  if to_regclass('public.shared_links') is null then
    raise notice 'skipping shared_links: table not present';
    return;
  end if;
  if not exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'shared_links'
      and column_name = 'organization_id'
  ) then
    raise notice 'skipping shared_links: required organization_id column not present';
    return;
  end if;

  execute 'alter table public.shared_links enable row level security';
  execute 'drop policy if exists "shared_links_select_member" on public.shared_links';
  execute 'create policy "shared_links_select_member" on public.shared_links for select to authenticated using (public.is_org_member(organization_id))';
end
$$;

do $$
begin
  if to_regclass('public.service_comments') is null then
    raise notice 'skipping service_comments: table not present';
    return;
  end if;
  if not exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'service_comments'
      and column_name = 'organization_id'
  ) then
    raise notice 'skipping service_comments: required organization_id column not present';
    return;
  end if;

  execute 'alter table public.service_comments enable row level security';
  execute 'drop policy if exists "service_comments_select_member" on public.service_comments';
  execute 'create policy "service_comments_select_member" on public.service_comments for select to authenticated using (public.is_org_member(organization_id))';
end
$$;

do $$
begin
  if to_regclass('public.accounting_exports') is null then
    raise notice 'skipping accounting_exports: table not present';
    return;
  end if;
  if not exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'accounting_exports'
      and column_name = 'organization_id'
  ) then
    raise notice 'skipping accounting_exports: required organization_id column not present';
    return;
  end if;

  execute 'alter table public.accounting_exports enable row level security';
  execute 'drop policy if exists "accounting_exports_select_member" on public.accounting_exports';
  execute 'create policy "accounting_exports_select_member" on public.accounting_exports for select to authenticated using (public.is_org_member(organization_id))';
end
$$;

do $$
begin
  if to_regclass('public.business_service_catalog') is null then
    raise notice 'skipping business_service_catalog: table not present';
    return;
  end if;
  if not exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'business_service_catalog'
      and column_name = 'organization_id'
  ) then
    raise notice 'skipping business_service_catalog: required organization_id column not present';
    return;
  end if;

  execute 'alter table public.business_service_catalog enable row level security';
  execute 'drop policy if exists "business_service_catalog_select_member" on public.business_service_catalog';
  execute 'create policy "business_service_catalog_select_member" on public.business_service_catalog for select to authenticated using (public.is_org_member(organization_id))';
end
$$;

do $$
begin
  if to_regclass('public.business_bookings') is null then
    raise notice 'skipping business_bookings: table not present';
    return;
  end if;
  if not exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'business_bookings'
      and column_name = 'organization_id'
  ) then
    raise notice 'skipping business_bookings: required organization_id column not present';
    return;
  end if;

  execute 'alter table public.business_bookings enable row level security';
  execute 'drop policy if exists "business_bookings_select_member" on public.business_bookings';
  execute 'create policy "business_bookings_select_member" on public.business_bookings for select to authenticated using (public.is_org_member(organization_id))';
end
$$;

do $$
begin
  if to_regclass('public.customer_records') is null then
    raise notice 'skipping customer_records: table not present';
    return;
  end if;
  if not exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'customer_records'
      and column_name = 'organization_id'
  ) then
    raise notice 'skipping customer_records: required organization_id column not present';
    return;
  end if;

  execute 'alter table public.customer_records enable row level security';
  execute 'drop policy if exists "customer_records_select_member" on public.customer_records';
  execute 'create policy "customer_records_select_member" on public.customer_records for select to authenticated using (public.is_org_member(organization_id))';
end
$$;

do $$
begin
  if to_regclass('public.customers') is null then
    raise notice 'skipping customers: table not present';
    return;
  end if;
  if not exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'customers'
      and column_name = 'organization_id'
  ) then
    raise notice 'skipping customers: required organization_id column not present';
    return;
  end if;

  execute 'alter table public.customers enable row level security';
  execute 'drop policy if exists "customers_select_member" on public.customers';
  execute 'create policy "customers_select_member" on public.customers for select to authenticated using (public.is_org_member(organization_id))';
end
$$;

do $$
begin
  if to_regclass('public.customer_invoices') is null then
    raise notice 'skipping customer_invoices: table not present';
    return;
  end if;
  if not exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'customer_invoices'
      and column_name = 'organization_id'
  ) then
    raise notice 'skipping customer_invoices: required organization_id column not present';
    return;
  end if;

  execute 'alter table public.customer_invoices enable row level security';
  execute 'drop policy if exists "customer_invoices_select_member" on public.customer_invoices';
  execute 'create policy "customer_invoices_select_member" on public.customer_invoices for select to authenticated using (public.is_org_member(organization_id))';
end
$$;

do $$
begin
  if to_regclass('public.customer_invoice_lines') is null then
    raise notice 'skipping customer_invoice_lines: table not present';
    return;
  end if;
  if not exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'customer_invoice_lines'
      and column_name = 'organization_id'
  ) then
    raise notice 'skipping customer_invoice_lines: required organization_id column not present';
    return;
  end if;

  execute 'alter table public.customer_invoice_lines enable row level security';
  execute 'drop policy if exists "customer_invoice_lines_select_member" on public.customer_invoice_lines';
  execute 'create policy "customer_invoice_lines_select_member" on public.customer_invoice_lines for select to authenticated using (public.is_org_member(organization_id))';
end
$$;

do $$
begin
  if to_regclass('public.customer_invoice_payments') is null then
    raise notice 'skipping customer_invoice_payments: table not present';
    return;
  end if;
  if not exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'customer_invoice_payments'
      and column_name = 'organization_id'
  ) then
    raise notice 'skipping customer_invoice_payments: required organization_id column not present';
    return;
  end if;

  execute 'alter table public.customer_invoice_payments enable row level security';
  execute 'drop policy if exists "customer_invoice_payments_select_member" on public.customer_invoice_payments';
  execute 'create policy "customer_invoice_payments_select_member" on public.customer_invoice_payments for select to authenticated using (public.is_org_member(organization_id))';
end
$$;

do $$
begin
  if to_regclass('public.quotes') is null then
    raise notice 'skipping quotes: table not present';
    return;
  end if;
  if not exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'quotes'
      and column_name = 'organization_id'
  ) then
    raise notice 'skipping quotes: required organization_id column not present';
    return;
  end if;

  execute 'alter table public.quotes enable row level security';
  execute 'drop policy if exists "quotes_select_member" on public.quotes';
  execute 'create policy "quotes_select_member" on public.quotes for select to authenticated using (public.is_org_member(organization_id))';
end
$$;

do $$
begin
  if to_regclass('public.module_outputs') is null then
    raise notice 'skipping module_outputs: table not present';
    return;
  end if;
  if not exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'module_outputs'
      and column_name = 'organization_id'
  ) then
    raise notice 'skipping module_outputs: required organization_id column not present';
    return;
  end if;

  execute 'alter table public.module_outputs enable row level security';
  execute 'drop policy if exists "module_outputs_select_member" on public.module_outputs';
  execute 'create policy "module_outputs_select_member" on public.module_outputs for select to authenticated using (public.is_org_member(organization_id))';
end
$$;

do $$
begin
  if to_regclass('public.service_deliverables') is null then
    raise notice 'skipping service_deliverables: table not present';
    return;
  end if;
  if not exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'service_deliverables'
      and column_name = 'organization_id'
  ) then
    raise notice 'skipping service_deliverables: required organization_id column not present';
    return;
  end if;

  execute 'alter table public.service_deliverables enable row level security';
  execute 'drop policy if exists "service_deliverables_select_member" on public.service_deliverables';
  execute 'create policy "service_deliverables_select_member" on public.service_deliverables for select to authenticated using (public.is_org_member(organization_id))';
end
$$;

do $$
begin
  if to_regclass('public.service_request_events') is null then
    raise notice 'skipping service_request_events: table not present';
    return;
  end if;
  if not exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'service_request_events'
      and column_name = 'organization_id'
  ) then
    raise notice 'skipping service_request_events: required organization_id column not present';
    return;
  end if;

  execute 'alter table public.service_request_events enable row level security';
  execute 'drop policy if exists "service_request_events_select_member" on public.service_request_events';
  execute 'create policy "service_request_events_select_member" on public.service_request_events for select to authenticated using (public.is_org_member(organization_id))';
end
$$;

do $$
begin
  if to_regclass('public.service_requests') is null then
    raise notice 'skipping service_requests: table not present';
    return;
  end if;
  if not exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'service_requests'
      and column_name = 'organization_id'
  ) then
    raise notice 'skipping service_requests: required organization_id column not present';
    return;
  end if;

  execute 'alter table public.service_requests enable row level security';
  execute 'drop policy if exists "service_requests_select_member" on public.service_requests';
  execute 'create policy "service_requests_select_member" on public.service_requests for select to authenticated using (public.is_org_member(organization_id))';
end
$$;

do $$
begin
  if to_regclass('public.sonara_formula_results') is null then
    raise notice 'skipping sonara_formula_results: table not present';
    return;
  end if;
  if not exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'sonara_formula_results'
      and column_name = 'organization_id'
  ) then
    raise notice 'skipping sonara_formula_results: required organization_id column not present';
    return;
  end if;

  execute 'alter table public.sonara_formula_results enable row level security';
  execute 'drop policy if exists "sonara_formula_results_select_member" on public.sonara_formula_results';
  execute 'create policy "sonara_formula_results_select_member" on public.sonara_formula_results for select to authenticated using (public.is_org_member(organization_id))';
end
$$;

do $$
begin
  if to_regclass('public.research_sources') is null then
    raise notice 'skipping research_sources: table not present';
    return;
  end if;
  if not exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'research_sources'
      and column_name = 'organization_id'
  ) then
    raise notice 'skipping research_sources: required organization_id column not present';
    return;
  end if;

  execute 'alter table public.research_sources enable row level security';
  execute 'drop policy if exists "research_sources_select_member" on public.research_sources';
  execute 'create policy "research_sources_select_member" on public.research_sources for select to authenticated using (public.is_org_member(organization_id))';
end
$$;

do $$
begin
  if to_regclass('public.audio_assets') is null then
    raise notice 'skipping audio_assets: table not present';
    return;
  end if;
  if not exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'audio_assets'
      and column_name = 'organization_id'
  ) then
    raise notice 'skipping audio_assets: required organization_id column not present';
    return;
  end if;

  execute 'alter table public.audio_assets enable row level security';
  execute 'drop policy if exists "audio_assets_select_member" on public.audio_assets';
  execute 'create policy "audio_assets_select_member" on public.audio_assets for select to authenticated using (public.is_org_member(organization_id))';
end
$$;

do $$
begin
  if to_regclass('public.automation_rules') is null then
    raise notice 'skipping automation_rules: table not present';
    return;
  end if;
  if not exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'automation_rules'
      and column_name = 'organization_id'
  ) then
    raise notice 'skipping automation_rules: required organization_id column not present';
    return;
  end if;

  execute 'alter table public.automation_rules enable row level security';
  execute 'drop policy if exists "automation_rules_select_member" on public.automation_rules';
  execute 'create policy "automation_rules_select_member" on public.automation_rules for select to authenticated using (public.is_org_member(organization_id))';
end
$$;

do $$
begin
  if to_regclass('public.business_workspaces') is null then
    raise notice 'skipping business_workspaces: table not present';
    return;
  end if;
  if not exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'business_workspaces'
      and column_name = 'organization_id'
  ) then
    raise notice 'skipping business_workspaces: required organization_id column not present';
    return;
  end if;

  execute 'alter table public.business_workspaces enable row level security';
  execute 'drop policy if exists "business_workspaces_select_member" on public.business_workspaces';
  execute 'create policy "business_workspaces_select_member" on public.business_workspaces for select to authenticated using (public.is_org_member(organization_id))';
end
$$;

do $$
begin
  if to_regclass('public.creator_generation_jobs') is null then
    raise notice 'skipping creator_generation_jobs: table not present';
    return;
  end if;
  if not exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'creator_generation_jobs'
      and column_name = 'organization_id'
  ) then
    raise notice 'skipping creator_generation_jobs: required organization_id column not present';
    return;
  end if;

  execute 'alter table public.creator_generation_jobs enable row level security';
  execute 'drop policy if exists "creator_generation_jobs_select_member" on public.creator_generation_jobs';
  execute 'create policy "creator_generation_jobs_select_member" on public.creator_generation_jobs for select to authenticated using (public.is_org_member(organization_id))';
end
$$;

do $$
begin
  if to_regclass('public.creator_voice_consents') is null then
    raise notice 'skipping creator_voice_consents: table not present';
    return;
  end if;
  if not exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'creator_voice_consents'
      and column_name = 'organization_id'
  ) then
    raise notice 'skipping creator_voice_consents: required organization_id column not present';
    return;
  end if;

  execute 'alter table public.creator_voice_consents enable row level security';
  execute 'drop policy if exists "creator_voice_consents_select_member" on public.creator_voice_consents';
  execute 'create policy "creator_voice_consents_select_member" on public.creator_voice_consents for select to authenticated using (public.is_org_member(organization_id))';
end
$$;

do $$
begin
  if to_regclass('public.employee_announcements') is null then
    raise notice 'skipping employee_announcements: table not present';
    return;
  end if;
  if not exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'employee_announcements'
      and column_name = 'organization_id'
  ) then
    raise notice 'skipping employee_announcements: required organization_id column not present';
    return;
  end if;

  execute 'alter table public.employee_announcements enable row level security';
  execute 'drop policy if exists "employee_announcements_select_member" on public.employee_announcements';
  execute 'create policy "employee_announcements_select_member" on public.employee_announcements for select to authenticated using (public.is_org_member(organization_id))';
end
$$;

do $$
begin
  if to_regclass('public.employee_schedules') is null then
    raise notice 'skipping employee_schedules: table not present';
    return;
  end if;
  if not exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'employee_schedules'
      and column_name = 'organization_id'
  ) then
    raise notice 'skipping employee_schedules: required organization_id column not present';
    return;
  end if;

  execute 'alter table public.employee_schedules enable row level security';
  execute 'drop policy if exists "employee_schedules_select_member" on public.employee_schedules';
  execute 'create policy "employee_schedules_select_member" on public.employee_schedules for select to authenticated using (public.is_org_member(organization_id))';
end
$$;

do $$
begin
  if to_regclass('public.employee_tasks') is null then
    raise notice 'skipping employee_tasks: table not present';
    return;
  end if;
  if not exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'employee_tasks'
      and column_name = 'organization_id'
  ) then
    raise notice 'skipping employee_tasks: required organization_id column not present';
    return;
  end if;

  execute 'alter table public.employee_tasks enable row level security';
  execute 'drop policy if exists "employee_tasks_select_member" on public.employee_tasks';
  execute 'create policy "employee_tasks_select_member" on public.employee_tasks for select to authenticated using (public.is_org_member(organization_id))';
end
$$;

do $$
begin
  if to_regclass('public.employee_time_entries') is null then
    raise notice 'skipping employee_time_entries: table not present';
    return;
  end if;
  if not exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'employee_time_entries'
      and column_name = 'organization_id'
  ) then
    raise notice 'skipping employee_time_entries: required organization_id column not present';
    return;
  end if;

  execute 'alter table public.employee_time_entries enable row level security';
  execute 'drop policy if exists "employee_time_entries_select_member" on public.employee_time_entries';
  execute 'create policy "employee_time_entries_select_member" on public.employee_time_entries for select to authenticated using (public.is_org_member(organization_id))';
end
$$;

do $$
begin
  if to_regclass('public.growth_audience_segments') is null then
    raise notice 'skipping growth_audience_segments: table not present';
    return;
  end if;
  if not exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'growth_audience_segments'
      and column_name = 'organization_id'
  ) then
    raise notice 'skipping growth_audience_segments: required organization_id column not present';
    return;
  end if;

  execute 'alter table public.growth_audience_segments enable row level security';
  execute 'drop policy if exists "growth_audience_segments_select_member" on public.growth_audience_segments';
  execute 'create policy "growth_audience_segments_select_member" on public.growth_audience_segments for select to authenticated using (public.is_org_member(organization_id))';
end
$$;

do $$
begin
  if to_regclass('public.growth_campaigns') is null then
    raise notice 'skipping growth_campaigns: table not present';
    return;
  end if;
  if not exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'growth_campaigns'
      and column_name = 'organization_id'
  ) then
    raise notice 'skipping growth_campaigns: required organization_id column not present';
    return;
  end if;

  execute 'alter table public.growth_campaigns enable row level security';
  execute 'drop policy if exists "growth_campaigns_select_member" on public.growth_campaigns';
  execute 'create policy "growth_campaigns_select_member" on public.growth_campaigns for select to authenticated using (public.is_org_member(organization_id))';
end
$$;

do $$
begin
  if to_regclass('public.growth_contact_consents') is null then
    raise notice 'skipping growth_contact_consents: table not present';
    return;
  end if;
  if not exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'growth_contact_consents'
      and column_name = 'organization_id'
  ) then
    raise notice 'skipping growth_contact_consents: required organization_id column not present';
    return;
  end if;

  execute 'alter table public.growth_contact_consents enable row level security';
  execute 'drop policy if exists "growth_contact_consents_select_member" on public.growth_contact_consents';
  execute 'create policy "growth_contact_consents_select_member" on public.growth_contact_consents for select to authenticated using (public.is_org_member(organization_id))';
end
$$;

do $$
begin
  if to_regclass('public.growth_content_queue') is null then
    raise notice 'skipping growth_content_queue: table not present';
    return;
  end if;
  if not exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'growth_content_queue'
      and column_name = 'organization_id'
  ) then
    raise notice 'skipping growth_content_queue: required organization_id column not present';
    return;
  end if;

  execute 'alter table public.growth_content_queue enable row level security';
  execute 'drop policy if exists "growth_content_queue_select_member" on public.growth_content_queue';
  execute 'create policy "growth_content_queue_select_member" on public.growth_content_queue for select to authenticated using (public.is_org_member(organization_id))';
end
$$;

do $$
begin
  if to_regclass('public.growth_conversions') is null then
    raise notice 'skipping growth_conversions: table not present';
    return;
  end if;
  if not exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'growth_conversions'
      and column_name = 'organization_id'
  ) then
    raise notice 'skipping growth_conversions: required organization_id column not present';
    return;
  end if;

  execute 'alter table public.growth_conversions enable row level security';
  execute 'drop policy if exists "growth_conversions_select_member" on public.growth_conversions';
  execute 'create policy "growth_conversions_select_member" on public.growth_conversions for select to authenticated using (public.is_org_member(organization_id))';
end
$$;

do $$
begin
  if to_regclass('public.growth_experiments') is null then
    raise notice 'skipping growth_experiments: table not present';
    return;
  end if;
  if not exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'growth_experiments'
      and column_name = 'organization_id'
  ) then
    raise notice 'skipping growth_experiments: required organization_id column not present';
    return;
  end if;

  execute 'alter table public.growth_experiments enable row level security';
  execute 'drop policy if exists "growth_experiments_select_member" on public.growth_experiments';
  execute 'create policy "growth_experiments_select_member" on public.growth_experiments for select to authenticated using (public.is_org_member(organization_id))';
end
$$;

do $$
begin
  if to_regclass('public.growth_leads') is null then
    raise notice 'skipping growth_leads: table not present';
    return;
  end if;
  if not exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'growth_leads'
      and column_name = 'organization_id'
  ) then
    raise notice 'skipping growth_leads: required organization_id column not present';
    return;
  end if;

  execute 'alter table public.growth_leads enable row level security';
  execute 'drop policy if exists "growth_leads_select_member" on public.growth_leads';
  execute 'create policy "growth_leads_select_member" on public.growth_leads for select to authenticated using (public.is_org_member(organization_id))';
end
$$;

do $$
begin
  if to_regclass('public.growth_metric_snapshots') is null then
    raise notice 'skipping growth_metric_snapshots: table not present';
    return;
  end if;
  if not exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'growth_metric_snapshots'
      and column_name = 'organization_id'
  ) then
    raise notice 'skipping growth_metric_snapshots: required organization_id column not present';
    return;
  end if;

  execute 'alter table public.growth_metric_snapshots enable row level security';
  execute 'drop policy if exists "growth_metric_snapshots_select_member" on public.growth_metric_snapshots';
  execute 'create policy "growth_metric_snapshots_select_member" on public.growth_metric_snapshots for select to authenticated using (public.is_org_member(organization_id))';
end
$$;

do $$
begin
  if to_regclass('public.growth_provider_jobs') is null then
    raise notice 'skipping growth_provider_jobs: table not present';
    return;
  end if;
  if not exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'growth_provider_jobs'
      and column_name = 'organization_id'
  ) then
    raise notice 'skipping growth_provider_jobs: required organization_id column not present';
    return;
  end if;

  execute 'alter table public.growth_provider_jobs enable row level security';
  execute 'drop policy if exists "growth_provider_jobs_select_member" on public.growth_provider_jobs';
  execute 'create policy "growth_provider_jobs_select_member" on public.growth_provider_jobs for select to authenticated using (public.is_org_member(organization_id))';
end
$$;

do $$
begin
  if to_regclass('public.growth_touchpoints') is null then
    raise notice 'skipping growth_touchpoints: table not present';
    return;
  end if;
  if not exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'growth_touchpoints'
      and column_name = 'organization_id'
  ) then
    raise notice 'skipping growth_touchpoints: required organization_id column not present';
    return;
  end if;

  execute 'alter table public.growth_touchpoints enable row level security';
  execute 'drop policy if exists "growth_touchpoints_select_member" on public.growth_touchpoints';
  execute 'create policy "growth_touchpoints_select_member" on public.growth_touchpoints for select to authenticated using (public.is_org_member(organization_id))';
end
$$;

do $$
begin
  if to_regclass('public.inventory_items') is null then
    raise notice 'skipping inventory_items: table not present';
    return;
  end if;
  if not exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'inventory_items'
      and column_name = 'organization_id'
  ) then
    raise notice 'skipping inventory_items: required organization_id column not present';
    return;
  end if;

  execute 'alter table public.inventory_items enable row level security';
  execute 'drop policy if exists "inventory_items_select_member" on public.inventory_items';
  execute 'create policy "inventory_items_select_member" on public.inventory_items for select to authenticated using (public.is_org_member(organization_id))';
end
$$;

do $$
begin
  if to_regclass('public.location_events') is null then
    raise notice 'skipping location_events: table not present';
    return;
  end if;
  if not exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'location_events'
      and column_name = 'organization_id'
  ) then
    raise notice 'skipping location_events: required organization_id column not present';
    return;
  end if;

  execute 'alter table public.location_events enable row level security';
  execute 'drop policy if exists "location_events_select_member" on public.location_events';
  execute 'create policy "location_events_select_member" on public.location_events for select to authenticated using (public.is_org_member(organization_id))';
end
$$;

do $$
begin
  if to_regclass('public.location_zones') is null then
    raise notice 'skipping location_zones: table not present';
    return;
  end if;
  if not exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'location_zones'
      and column_name = 'organization_id'
  ) then
    raise notice 'skipping location_zones: required organization_id column not present';
    return;
  end if;

  execute 'alter table public.location_zones enable row level security';
  execute 'drop policy if exists "location_zones_select_member" on public.location_zones';
  execute 'create policy "location_zones_select_member" on public.location_zones for select to authenticated using (public.is_org_member(organization_id))';
end
$$;

do $$
begin
  if to_regclass('public.market_intelligence_competitors') is null then
    raise notice 'skipping market_intelligence_competitors: table not present';
    return;
  end if;
  if not exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'market_intelligence_competitors'
      and column_name = 'organization_id'
  ) then
    raise notice 'skipping market_intelligence_competitors: required organization_id column not present';
    return;
  end if;

  execute 'alter table public.market_intelligence_competitors enable row level security';
  execute 'drop policy if exists "market_intelligence_competitors_select_member" on public.market_intelligence_competitors';
  execute 'create policy "market_intelligence_competitors_select_member" on public.market_intelligence_competitors for select to authenticated using (public.is_org_member(organization_id))';
end
$$;

do $$
begin
  if to_regclass('public.market_intelligence_opportunities') is null then
    raise notice 'skipping market_intelligence_opportunities: table not present';
    return;
  end if;
  if not exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'market_intelligence_opportunities'
      and column_name = 'organization_id'
  ) then
    raise notice 'skipping market_intelligence_opportunities: required organization_id column not present';
    return;
  end if;

  execute 'alter table public.market_intelligence_opportunities enable row level security';
  execute 'drop policy if exists "market_intelligence_opportunities_select_member" on public.market_intelligence_opportunities';
  execute 'create policy "market_intelligence_opportunities_select_member" on public.market_intelligence_opportunities for select to authenticated using (public.is_org_member(organization_id))';
end
$$;

do $$
begin
  if to_regclass('public.market_intelligence_reviews') is null then
    raise notice 'skipping market_intelligence_reviews: table not present';
    return;
  end if;
  if not exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'market_intelligence_reviews'
      and column_name = 'organization_id'
  ) then
    raise notice 'skipping market_intelligence_reviews: required organization_id column not present';
    return;
  end if;

  execute 'alter table public.market_intelligence_reviews enable row level security';
  execute 'drop policy if exists "market_intelligence_reviews_select_member" on public.market_intelligence_reviews';
  execute 'create policy "market_intelligence_reviews_select_member" on public.market_intelligence_reviews for select to authenticated using (public.is_org_member(organization_id))';
end
$$;

do $$
begin
  if to_regclass('public.market_intelligence_segments') is null then
    raise notice 'skipping market_intelligence_segments: table not present';
    return;
  end if;
  if not exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'market_intelligence_segments'
      and column_name = 'organization_id'
  ) then
    raise notice 'skipping market_intelligence_segments: required organization_id column not present';
    return;
  end if;

  execute 'alter table public.market_intelligence_segments enable row level security';
  execute 'drop policy if exists "market_intelligence_segments_select_member" on public.market_intelligence_segments';
  execute 'create policy "market_intelligence_segments_select_member" on public.market_intelligence_segments for select to authenticated using (public.is_org_member(organization_id))';
end
$$;

do $$
begin
  if to_regclass('public.market_intelligence_signals') is null then
    raise notice 'skipping market_intelligence_signals: table not present';
    return;
  end if;
  if not exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'market_intelligence_signals'
      and column_name = 'organization_id'
  ) then
    raise notice 'skipping market_intelligence_signals: required organization_id column not present';
    return;
  end if;

  execute 'alter table public.market_intelligence_signals enable row level security';
  execute 'drop policy if exists "market_intelligence_signals_select_member" on public.market_intelligence_signals';
  execute 'create policy "market_intelligence_signals_select_member" on public.market_intelligence_signals for select to authenticated using (public.is_org_member(organization_id))';
end
$$;

do $$
begin
  if to_regclass('public.menu_items') is null then
    raise notice 'skipping menu_items: table not present';
    return;
  end if;
  if not exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'menu_items'
      and column_name = 'organization_id'
  ) then
    raise notice 'skipping menu_items: required organization_id column not present';
    return;
  end if;

  execute 'alter table public.menu_items enable row level security';
  execute 'drop policy if exists "menu_items_select_member" on public.menu_items';
  execute 'create policy "menu_items_select_member" on public.menu_items for select to authenticated using (public.is_org_member(organization_id))';
end
$$;

do $$
begin
  if to_regclass('public.motion_sensor_events') is null then
    raise notice 'skipping motion_sensor_events: table not present';
    return;
  end if;
  if not exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'motion_sensor_events'
      and column_name = 'organization_id'
  ) then
    raise notice 'skipping motion_sensor_events: required organization_id column not present';
    return;
  end if;

  execute 'alter table public.motion_sensor_events enable row level security';
  execute 'drop policy if exists "motion_sensor_events_select_member" on public.motion_sensor_events';
  execute 'create policy "motion_sensor_events_select_member" on public.motion_sensor_events for select to authenticated using (public.is_org_member(organization_id))';
end
$$;

do $$
begin
  if to_regclass('public.music_projects') is null then
    raise notice 'skipping music_projects: table not present';
    return;
  end if;
  if not exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'music_projects'
      and column_name = 'organization_id'
  ) then
    raise notice 'skipping music_projects: required organization_id column not present';
    return;
  end if;

  execute 'alter table public.music_projects enable row level security';
  execute 'drop policy if exists "music_projects_select_member" on public.music_projects';
  execute 'create policy "music_projects_select_member" on public.music_projects for select to authenticated using (public.is_org_member(organization_id))';
end
$$;

do $$
begin
  if to_regclass('public.product_lifecycle_initiatives') is null then
    raise notice 'skipping product_lifecycle_initiatives: table not present';
    return;
  end if;
  if not exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'product_lifecycle_initiatives'
      and column_name = 'organization_id'
  ) then
    raise notice 'skipping product_lifecycle_initiatives: required organization_id column not present';
    return;
  end if;

  execute 'alter table public.product_lifecycle_initiatives enable row level security';
  execute 'drop policy if exists "product_lifecycle_initiatives_select_member" on public.product_lifecycle_initiatives';
  execute 'create policy "product_lifecycle_initiatives_select_member" on public.product_lifecycle_initiatives for select to authenticated using (public.is_org_member(organization_id))';
end
$$;

do $$
begin
  if to_regclass('public.recipe_cards') is null then
    raise notice 'skipping recipe_cards: table not present';
    return;
  end if;
  if not exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'recipe_cards'
      and column_name = 'organization_id'
  ) then
    raise notice 'skipping recipe_cards: required organization_id column not present';
    return;
  end if;

  execute 'alter table public.recipe_cards enable row level security';
  execute 'drop policy if exists "recipe_cards_select_member" on public.recipe_cards';
  execute 'create policy "recipe_cards_select_member" on public.recipe_cards for select to authenticated using (public.is_org_member(organization_id))';
end
$$;

do $$
begin
  if to_regclass('public.tactile_events') is null then
    raise notice 'skipping tactile_events: table not present';
    return;
  end if;
  if not exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'tactile_events'
      and column_name = 'organization_id'
  ) then
    raise notice 'skipping tactile_events: required organization_id column not present';
    return;
  end if;

  execute 'alter table public.tactile_events enable row level security';
  execute 'drop policy if exists "tactile_events_select_member" on public.tactile_events';
  execute 'create policy "tactile_events_select_member" on public.tactile_events for select to authenticated using (public.is_org_member(organization_id))';
end
$$;

do $$
begin
  if to_regclass('public.vendor_invoices') is null then
    raise notice 'skipping vendor_invoices: table not present';
    return;
  end if;
  if not exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'vendor_invoices'
      and column_name = 'organization_id'
  ) then
    raise notice 'skipping vendor_invoices: required organization_id column not present';
    return;
  end if;

  execute 'alter table public.vendor_invoices enable row level security';
  execute 'drop policy if exists "vendor_invoices_select_member" on public.vendor_invoices';
  execute 'create policy "vendor_invoices_select_member" on public.vendor_invoices for select to authenticated using (public.is_org_member(organization_id))';
end
$$;


-- Person-scoped: these rows belong to one member, not to the organization.

do $$
begin
  if to_regclass('public.business_employee_profiles') is null then
    raise notice 'skipping business_employee_profiles: table not present';
    return;
  end if;
  if not exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'business_employee_profiles'
      and column_name = 'user_id'
  ) then
    raise notice 'skipping business_employee_profiles: required user_id column not present';
    return;
  end if;

  execute 'alter table public.business_employee_profiles enable row level security';
  execute 'drop policy if exists "business_employee_profiles_select_own" on public.business_employee_profiles';
  execute 'create policy "business_employee_profiles_select_own" on public.business_employee_profiles for select to authenticated using (auth.uid() = user_id)';
end
$$;

do $$
begin
  if to_regclass('public.sonara_platforms') is null then
    raise notice 'skipping sonara_platforms: table not present';
    return;
  end if;
  if not exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'sonara_platforms'
      and column_name = 'user_id'
  ) then
    raise notice 'skipping sonara_platforms: required user_id column not present';
    return;
  end if;

  execute 'alter table public.sonara_platforms enable row level security';
  execute 'drop policy if exists "sonara_platforms_select_own" on public.sonara_platforms';
  execute 'create policy "sonara_platforms_select_own" on public.sonara_platforms for select to authenticated using (auth.uid() = user_id)';
end
$$;

do $$
begin
  if to_regclass('public.user_notifications') is null then
    raise notice 'skipping user_notifications: table not present';
    return;
  end if;
  if not exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'user_notifications'
      and column_name = 'user_id'
  ) then
    raise notice 'skipping user_notifications: required user_id column not present';
    return;
  end if;

  execute 'alter table public.user_notifications enable row level security';
  execute 'drop policy if exists "user_notifications_select_own" on public.user_notifications';
  execute 'create policy "user_notifications_select_own" on public.user_notifications for select to authenticated using (auth.uid() = user_id)';
end
$$;

do $$
begin
  if to_regclass('public.user_preferences') is null then
    raise notice 'skipping user_preferences: table not present';
    return;
  end if;
  if not exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'user_preferences'
      and column_name = 'user_id'
  ) then
    raise notice 'skipping user_preferences: required user_id column not present';
    return;
  end if;

  execute 'alter table public.user_preferences enable row level security';
  execute 'drop policy if exists "user_preferences_select_own" on public.user_preferences';
  execute 'create policy "user_preferences_select_own" on public.user_preferences for select to authenticated using (auth.uid() = user_id)';
end
$$;
