export const githubRadarCategories = [
  "app builder",
  "internal tools",
  "CRM",
  "support inbox",
  "commerce",
  "POS",
  "scheduling",
  "notification infrastructure",
  "feature flags",
  "product analytics",
  "surveys",
  "e-signature",
  "document AI",
  "OCR",
  "vector database",
  "local database",
  "local AI",
  "workflow automation",
  "AI agents",
  "MCP servers",
  "observability",
  "error tracking",
  "secret scanning",
  "vulnerability scanning",
  "static analysis",
  "database tools",
  "storage tools",
  "search tools",
  "email platform",
  "billing metering",
  "authorization",
  "identity",
  "file management",
  "media asset management",
  "social media management",
];
